### ISSUE TITLE
Lambda's ClickGUI doesn't work with ReplayMod

### ISSUE THREAD

**Issue by CoconutBin** [lambda-client/lambda-legacy#100]
**What mod?**
ReplyMod is a Mod that allows you to record, replay and share recordings of your gameplay to make it seem like you're a spectator.

**Logs**
 ReplayMod and Lambda can be Run at the same time

**Additional context**
 It can be run at the same time, but when done you would be unable to use the clickGUI

**Comment by scorbett123** [comment]
> ReplayMod and Lambda can be Run at the same time

Even if they can both be run at the same time there should still be logs created. Please can you send those.

**Comment by CoconutBin** [comment]
[2021-05-24-1.log.gz](https://github.com/lambda-client/lambda/files/6533651/2021-05-24-1.log.gz)

**Comment by scorbett123** [comment]
Does it work if you remove optifine?

**Comment by CoconutBin** [comment]
It doesn't work even if i remove optifine,

**Comment by Revvvy13** [comment]
I have been having a problem with Lambda and replay mod where Minecraft just won't launch, then returns an "error code 0."

**Comment by ToxicAven** [comment]
@Revvvy13 could you provide the full log please?

**Comment by ItCameFr0mMars** [comment]
I recently was doing some replaymod work, and you need to to ;toggle gui to disable the gui and also any other render modules such as NameTags

**Comment by ToxicAven** [comment]
This is just an incompatibility with replaymod and how it modifies the camera and screen controls.
