### ISSUE TITLE
crash when changing settings randomly

### ISSUE THREAD

**Issue by Sand-Turtle** [lambda-client/lambda-legacy#102]
**Describe the bug**[crash-2021-05-25_22.55.27-client.txt](https://github.com/lambda-client/lambda/files/6543741/crash-2021-05-25_22.55.27-client.txt)instacrash because of a invalid value it seems

**To Reproduce**
not sure

**Expected behavior**
not crash kek

**Debug info**

[crash-2021-05-25_22.55.27-client.txt](https://github.com/lambda-client/lambda/files/6543741/crash-2021-05-25_22.55.27-client.txt)**Additional context / media**

**Comment by Avanatiker** [comment]
Lol what setting did you use?

**Comment by Sand-Turtle** [comment]
> Lol what setting did you use?

Who tf knows XD

**Comment by scorbett123** [comment]
Is it possible that you could send your module config file?

**Comment by Sand-Turtle** [comment]
I have since changed it a lot but it happens while I was config in hwt and my mouse slipped ad I changed something behind it

**Comment by huddy987** [comment]
@Sand-Turtle Have you been able to reproduce this? If not we should close this issue

**Comment by Sand-Turtle** [comment]
Nope, plus ive left 2b
