### ISSUE TITLE
DiscordNotifs Module won't work

### ISSUE THREAD

**Issue by fudge92** [lambda-client/lambda-legacy#103]
**Describe the bug**
Whenever i try to turn on DiscordNotifs Module, it tells me set up the webhook url, avatar, and ID with `;discordnotifs` command. But whenever i try to set it up with the command, it says no such command found. 

**To Reproduce**
Fix `;discordnotifs` command

**Expected behavior**
It should work and accept the webhook url, avatar url and id. 

**Debug info**
![image](https://user-images.githubusercontent.com/83440724/120059136-20408680-c06d-11eb-8e61-62c23fcf53b5.png)

**Additional context / media**

Check this video : 
https://user-images.githubusercontent.com/83440724/120059022-634e2a00-c06c-11eb-9c50-0e2569385d7d.mp4

**Comment by czho** [comment]
That feature was bearly used by most people and was made into a plugin, goto the lambda gui and install chatplus to use this command / module

**Comment by fudge92** [comment]
> That feature was bearly used by most people and was made into a plugin, goto the lambda gui and install chatplus to use this command / module

what to do after installing ChatPlus, i have installed it


/chatplus and /discordnotifs is doing nothing. Or do i need to be in server to enable it ? 


https://user-images.githubusercontent.com/83440724/120059274-0fdcdb80-c06e-11eb-860a-382759a85cf6.mp4

**Comment by Avanatiker** [comment]
you are supposed to type `;discordnotifs` not `/discordnotifs`

**Comment by fudge92** [comment]
https://user-images.githubusercontent.com/83440724/120059022-634e2a00-c06c-11eb-9c50-0e2569385d7d.mp4 
Please check this video, i used `;discordnotifs` but that didn't do anything

**Comment by scorbett123** [comment]
Does the command ;help show discordnotifs?

**Comment by fudge92** [comment]
> Does the command ;help show discordnotifs?

no

**Comment by scorbett123** [comment]
What is the result of ;plugin list

**Comment by soham9229** [comment]
![image](https://user-images.githubusercontent.com/83440724/120376054-0cc94000-c339-11eb-8802-61f396de435d.png)

**Comment by fudge92** [comment]
![image](https://user-images.githubusercontent.com/83440724/120376104-181c6b80-c339-11eb-9c67-2cebe7ce5534.png)

**Comment by scorbett123** [comment]
Wait, sorry, been trying to diagnose a problem that doesn't exist, the command has been removed, however you can edit all of the settings through the module in the click GUI.

**Comment by fudge92** [comment]
ok, thanks
