### ISSUE TITLE
Some Keys arent supported as hotkeys [ Bug ]

### ISSUE THREAD

**Issue by Tokara1** [lambda-client/lambda-legacy#107]
**Describe the bug**
Some Keys on the keyboard are not supported to be set as hotkeys for modules.
Trying to set them as bind will reset the option Bind in the module to none instead of adding the keybind with the unsupported keys.

**To Reproduce**

1. Go to any module that can be toggled 
2. Open the module options ( right click )
3. Go to <Bind> 
4. click that and try setting one of the keys in the screenshot below ( additional context/ media) as keybind for the module

**Expected behavior**
I would expect it to set the keys i press (which are on english keyboards too) to be set as bind instead of setting the bind option to <none>

**Debug info**
![2021-06-02_17 25 51](https://user-images.githubusercontent.com/85032179/120508155-c7078880-c3c7-11eb-9ca2-7812f4e82bb4.png)

**Additional context / media**

![keys5lambda](https://user-images.githubusercontent.com/85032179/120509624-f7035b80-c3c8-11eb-8a38-e09219e822fb.jpeg)

**Comment by scorbett123** [comment]
What OS are you using?


Anyway, I can reproduce this but only with backspace. I believe that this is a limitation of lwjgl 2 so there would be very little that we can do to fix this. This is also frequently very OS / hardware based about what keys can be used and which can't.

**Comment by Tokara1** [comment]
I use Linux mint, but i never had any issues With other clients regarding this so i was guessing it is a Software issue mod side

**Comment by scorbett123** [comment]
> I use Linux mint, but i never had any issues With other clients regarding this so i was guessing it is a Software issue mod side

 The issue is is that lwjgl gives the keycode of 0 meaning that any one of these button (any not known to lwjgl 2) would seem to be pressed at the same time.

I can't reproduce this with all of these keys on windows and a quick search suggests that it is quite frequently OS specific about which keys return a value and which just return 0.
