### ISSUE TITLE
Make AutoEat Able to Eat with an Offhand

### ISSUE THREAD

**Issue by CoconutBin** [lambda-client/lambda-legacy#111]
**Is your feature request related to a problem? Please describe.**
AutoEat Always Eats from the Hotbar Instead of the Offhand

**Describe the solution you'd like**
An Offhand Mode for AutoEat

**Describe alternatives you've considered**
Manually Eating the Gapple

**Additional context**
No.

**Comment by czho** [comment]
Autoeat needs some work anyways, ill look into it if i get some time

**Comment by CoconutBin** [comment]
I think it's in #80
