### ISSUE TITLE
i have rhack, future and konas with lambida and it wont run when i do

### ISSUE THREAD

**Issue by mrhwe** [lambda-client/lambda-legacy#112]
This is the crash report

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Inertia Client (inertia)
Exit Code: -1

**Comment by ToxicAven** [comment]
add a ! to the beginning of the lambda client mod, and then remove all your mods and add them back 1 after another until it crashes.

**Comment by czho** [comment]
this is probably an issue with inertia client

**Comment by d1snin** [comment]
lambida :trollface:

**Comment by scorbett123** [comment]
Nah, have seen this with konas before. An ! Fixes it though.

**Comment by Avanatiker** [comment]
So it works now?

**Comment by huddy987** [comment]
No response, closing and assuming its resolved
