### ISSUE TITLE
crystalpvp.cc AutoEZ

### ISSUE THREAD

**Issue by CoconutBin** [lambda-client/lambda-legacy#118]
**Describe the bug**
AutoEZ doesn't work on crystalpvp.cc

**To Reproduce**

1. Go to crystalpvp.cc
2. Click on AutoEZ
3. Win a Fight

**Expected behavior**
AutoEZ says the prompt given (gg, ontop, ezHypixel)

**Debug info**
![image](https://user-images.githubusercontent.com/75740238/122426592-9116f680-cfba-11eb-80e3-77379d56ab32.png)

**Additional context / media**
using phobos clean 1.5.4 and cookie client, haven't tried it without the discussed modifications

**Comment by luxuwu** [comment]
its not just .cc on 50% of the servers i play on it dont work :/

**Comment by Avanatiker** [comment]
Maybe they block chat messages on kill? idk

**Comment by Natan515** [comment]
I guess they just block the message, cause there is no reason it will just work at some servers and in some not.

**Comment by ToxicAven** [comment]
If you do not use lambda's combat modules, AutoEZ will not trigger as they were never added as a target.
