### ISSUE TITLE
Too smol HUD elements

### ISSUE THREAD

**Issue by Avanatiker** [lambda-client/lambda-legacy#12]
We should add a default design for empty HUD elements to recognize them

https://cdn.discordapp.com/attachments/755242152895709275/836461605000052736/unknown.png

**Comment by scorbett123** [comment]
Would just increasing the minimum size be alright, or should there be some kind of image displayed, e.g. the logo?

**Comment by Avanatiker** [comment]
Image or smth that tells me what HUD it is. So that u can distinguish between BaritonePRocess and Entitylist etc
