### ISSUE TITLE
Encase idiots

### ISSUE THREAD

**Issue by HoratioGamer** [lambda-client/lambda-legacy#122]
**Is your feature request related to a problem? Please describe.**
The problem is, one idiot with crystals can greatly impede the progress of a group of pavers.   

A group of pavers has the ability to lay obsidian far faster than an idiot can break it.   

**Describe the solution you'd like**
Have a HighwayTools mode called Encase, where, it just encases an adversary in obsidian faster than he can get out of it.   The default behaviour would be to get one layer around the adversary, then move to points around him and thicken it.   

HighwayTools already agrees on the obsidian pattern on roads, and will cooperate in laying it.... it is just a different pattern.   

**Describe alternatives you've considered**
A cooperative crystal aura would be far more difficult to program, use HighwayTools strengths and numbers to solve the problem.   

He cannot crystal or use a sword from inside obsidian, at a distance that HighwayTools can lay obsidian.   Lay obsidian in a sponge pattern, so, as he tries to come out, it is inevitable he will show his feet at a hole.   Lay a 1-deep pit below him with a crystal in it, so, if he tries to go down, it can be detonated.   One player can hold him there while others escape.

**Comment by czho** [comment]
put this in the highway tools plugin repo, we need pvp highway tools baddly

**Comment by Avanatiker** [comment]
we need a full suite of modules that are coded to communicate decentralized to other players using the same domain

**Comment by HoratioGamer** [comment]
Decentralized communication??   

Or just have the same geometric model and use shuffle tasks, just like highway tools uses to accelerate cooperative building.   

Highway Tools only needs one PvP trick, if it is a good trick, and very frustrating to the attacker.   He expects to win, at worst, he is prepared to die and go at it again, but wasting his time algorithmically, endlessly, without ever even attracting the attention of the people running the AFK paving bots, that will bust him up.   It is like an ant tapping on your shoe to get your attention -- at some point he is just going to realize that he is insignificant.   Like how long does he want to spend not achieving his goals ?  Being ignored ?  

It is the way to get rid of a little brother who is pestering you.

**Comment by badcodehash** [comment]
Unnecessary imo. Highway builders don't encounter even nearly as much people as you'd expect. Use the default combat features. Best regards.

**Comment by HoratioGamer** [comment]
I disagree, current combat features will not do it.   Particularly because players will use HT afk, or will literally be away from their keyboard as it runs, you cannot have it set up to auto-crystal strangers who just happen to be travelling the highway at the same time.   It has to be a When Attacked, or triggered by a name on an Enemies List, the opposite of a Friends List.

**Comment by ToxicAven** [comment]
AutoTrap?
