### ISSUE TITLE
"Leave no Trace" mod

### ISSUE THREAD

**Issue by HoratioGamer** [lambda-client/lambda-legacy#128]
**Is your feature request related to a problem? Please describe.**
Right now, baritone leaves traces of player activity when using the ;b goto command or the ;b tunnel command.    It walks away from drops before they can be picked up by the player.  It places out of dimension blocks and out of structure blocks.  It creates a lot of pillars and scaffolds.   ;b backfill does backfill 2x1 tunnels most of the time.  Future travel automation mods are likely to leave traces also.

Even HighwayTools sometimes leaves drops behind, like shulkers, echests, obsidian and netherrack -- the netherrack is not valuable, but leaving the others is not optimal.   "Leave no Trace" would automatically leave a cleaner worksite.   

**Describe the solution you'd like**
We cannot cure all the problems with baritone, or its successors, but we can deal with a lot of common things to leave the traces left far more rare and harder to follow.
  
This is a battery of measures, each one to reduce the player's footprint as they travel.

 - detect when the player causes new drops to form it its immediate vicinity and make sure to pause Baritone to pick them up.
 - when in a dimension or biome, immediately move all out-of-biome or out-of-dimension blocks off the hot bar so that they are not available to baritone to use as fillers.   i.e. when stepping through a nether portal into the overworld, all netherrack is moved off the hotbar and overworld blocks are moved in.  
 - move the axe off the hotbar so baritone will stop chopping trees and will simply go around them.   
 - automatically destroy scaffolds behind you
 - automatically switch on backfill when it appears we are making a 2x1 tunnel with ;b tunnel.
 - automatically burn excess drops
 - in the overworld, move the silk touch pickaxe to the hotbar if one is available, and move others off the hotbar.   

**Describe alternatives you've considered**
Current and future automatic travel and other automated tools are likely to leave traces.   There is no alternative to this mod, it is a new invention.   

**Additional context**
A good traveler leaves no tracks.  -- Lao Tzu

**Comment by ItCameFr0mMars** [comment]
seems like more of an issue with baritone rather than lambda. you should go over to their repo and make an issue

**Comment by scorbett123** [comment]
> 

This is currently an issue on the baritone repository, so don't go and create another there as it will just be closed as a duplicate.

**Comment by czho** [comment]
The purpose of this module is completely defeated by the chad module known as newchunks
