### ISSUE TITLE
ClickGui drops FPS by a factor of 10

### ISSUE THREAD

**Issue by B2H990** [lambda-client/lambda-legacy#133]
**Describe the bug**
ClickGui drops FPS by a factor of 10

**To Reproduce**
Open ClickGui

**Expected behavior**
Have little to no noticeable performance impact

**Debug info**
Not relevant persistent across multiple machines

**Additional context / media**
https://i.ibb.co/M1VsxwK/2021-07-13-16-24-35.png
https://i.ibb.co/cwxwSnc/2021-07-13-16-25-33.png

**Comment by skidrrr** [comment]
same me to

**Comment by luxuwu** [comment]
dose not happen with me

**Comment by czho** [comment]
This needs looking into

**Comment by ToxicAven** [comment]
Closed as no other incidents have been reported since without logs.
