### ISSUE TITLE
the highwaytools plugin 

### ISSUE THREAD

**Issue by luxuwu** [lambda-client/lambda-legacy#136]
the highwaytools is very bugged due to it trying to place a block throw a block and it just brakes and gets stuck add a setting to tern this off or something idk

**Comment by IncognitoModeDev** [comment]
Ya it is bugged I already report it to the devs but they did not respond about it F

**Comment by Natan515** [comment]
This is not a problem with the lambda-client itself, it is a problem with the plugin - https://github.com/lambda-plugins/HighwayTools

**Comment by Avanatiker** [comment]
See @Natan515 comment
