### ISSUE TITLE
Client is crashing 

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#14]
.

**Comment by Avanatiker** [comment]
Umm thats not much info?

**Comment by Natan515** [comment]
Ye 1 sec

**Comment by Natan515** [comment]
[latest.log](https://github.com/lambda-client/lambda/files/6393435/latest.log)

**Comment by Natan515** [comment]
I tried it with the latest version, and it started fine and than it just crushed

**Comment by Luna5ama** [comment]
Stop using JDK 11
https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip

**Comment by Natan515** [comment]
Thanks it works now!
