### ISSUE TITLE
Plugin Hud Elements dont show config items

### ISSUE THREAD

**Issue by connorslade** [lambda-client/lambda-legacy#142]
**Describe the bug**
When I have a `PluginLabelHud` or `PluginHudElement` with setting controls defined that doesn't have the name of a default Lambda client HudElement the right click menu is empty.

**To Reproduce**
I made a plugin with [this](https://gist.github.com/Basicprogrammer10/fb4fcd9288be900faaca4ab7c5651626) code.

**Expected behavior**
I would expect the settings I defined to show up in the right click menu.

**Debug info**
![image](https://user-images.githubusercontent.com/50306817/130902161-5282c8e4-a626-4b3b-ad00-ebf84fe18bb3.png)

**Additional context / media**
![image](https://user-images.githubusercontent.com/50306817/130902179-cc90db0c-dfd9-419e-818b-bb9becda0e58.png)

**Comment by Avanatiker** [comment]
Thanks for the report. Its a known issue. We will work on that!

**Comment by Luna5ama** [comment]
Fixed in 251dc92
