### ISSUE TITLE
TemplarCosmetics Book Title Mod Crash

### ISSUE THREAD

**Issue by Lqnz** [lambda-client/lambda-legacy#143]
**Describe the bug**
Basically if I turn on the ChestStealer module and turned on the Book Title module in TemplarCosmetics, It would basically crash.
(Note that I am not using other clients, only Lambda and TemplarCosmetics ofc. And I didn't turned on any other modules on both clients)

**To Reproduce**
Here's a clip on how to reproduce it: https://youtu.be/qY1lIksGP3c

**Debug info**
Here's the crash log: https://pastebin.com/MQhJExQ4

**Comment by Avanatiker** [comment]
Thanks for the report. Unfortunately your mod screen seems to be specified as a container GUI so the module tries to steal items from the menu. Excluding it in lambda would possibly cause other problems. For now just disable the module while beeing in that menu.

**Comment by Lqnz** [comment]
> Thanks for the report. Unfortunately your mod screen seems to be specified as a container GUI so the module tries to steal items from the menu. Excluding it in lambda would possibly cause other problems. For now just disable the module while beeing in that menu.

Alright thanks man. I appreciate it!
