### ISSUE TITLE
Allow CrystalBasePlace to place while eating

### ISSUE THREAD

**Issue by jraffstar** [lambda-client/lambda-legacy#149]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To find a way to make CrystalBasePlace Able to place while eating or add a "While eating" Option

**Describe alternatives you've considered**
None

**Additional context**
Idk if this is a client compatibility issue but its probably not

**Comment by Luna5ama** [comment]
Turn off PauseForEating in CombatSetting
