### ISSUE TITLE
1.17.1 port

### ISSUE THREAD

**Issue by JaanDev** [lambda-client/lambda-legacy#150]
Hello! I wanted to ask, are you going to port lambda to newer versions of Minecraft(1.17.1 etc.)? I wanted to use lambda on a 1.17.1 server for bulding highways.

Or, maybe, i could port lambda myself? I know Java a bit.

**Comment by NepNep21** [comment]
Lambda is almost entirely kotlin, knowing java isn't enough, i have heard of plans to port it to newer versions, but nothing is a guarantee yet afaik, anyway, for now you can use viaforge

**Comment by JaanDev** [comment]
Ok, thanks

**Comment by scorbett123** [comment]
The current plan is that if we were to do anything with 1.17, then it will be creating an entire new mod for 1.16 / 17 in fabric most likely.

**Comment by Luna5ama** [comment]
You can use viaforge to play on server on newer version with 1.12.2 client.
