### ISSUE TITLE
Crashing On launch

### ISSUE THREAD

**Issue by ItCameFr0mMars** [lambda-client/lambda-legacy#153]
Attached is the log. Tried to run on a raspberry pi 4 running raspbian, seems to be some discordrpc error

[latest.log](https://github.com/lambda-client/lambda/files/7188794/latest.log)

**Comment by NepNep21** [comment]
Afaik this is caused by there not being arm binaries from discord/discord-rpc, which is deprecated, if you don't need rpc, you can just remove it and compile it yourself, but a permanent solution for everyone would be to use/make an implementation entirely without natively compiled code

**Comment by ItCameFr0mMars** [comment]
I tried to make one without dicordrpc, if you check my repos, but as i have no knowledge of java, it did not work

**Comment by NepNep21** [comment]
I can help you more with that in the discord server, ping me Nep Nep#3025

**Comment by ItCameFr0mMars** [comment]
sure!

**Comment by NepNep21** [comment]
I will try working on this once my current PR is merged/closed (i did a stupid thing)

**Comment by Luna5ama** [comment]
Remove the entire DiscordRPC module class and these lines should work

https://github.com/lambda-client/lambda/blob/897253f52820d74e1939a9e51652356b96272363/build.gradle.kts#L99-L101
https://github.com/lambda-client/lambda/blob/897253f52820d74e1939a9e51652356b96272363/src/main/kotlin/com/lambda/client/module/modules/client/Capes.kt#L12
https://github.com/lambda-client/lambda/blob/897253f52820d74e1939a9e51652356b96272363/src/main/kotlin/com/lambda/client/module/modules/client/Capes.kt#L94

**Comment by ItCameFr0mMars** [comment]
yeah but it won't build.

**Comment by terrified9** [comment]
#86 same happens to me. If you fix it or compile a working version, please reply or ping me🙏

**Comment by ItCameFr0mMars** [comment]
https://mega.nz/file/DbQRkSBa#LmpC7i-lqEwSYlmls5Jz8uRAZxPZj_dyg-fkTazN_GI

**Comment by NepNep21** [comment]
A 3rd party mega download shouldn't close this imo, as it's still an issue with lambda itself that can be fixed

**Comment by ItCameFr0mMars** [comment]
sorry, the link should be able to temporarily fix the problem, I'll reopen
