### ISSUE TITLE
its not building

### ISSUE THREAD

**Issue by master7720** [lambda-client/lambda-legacy#154]

**Comment by Avanatiker** [comment]
It's not working because a ForgeGradle dependency is down. We try to figure out a fix for this rn.

**Comment by master7720** [comment]
ah okk

**Comment by Avanatiker** [comment]
Rn it's only compiling for people who have already forge mapping stable inside the gradle cache from earlier

**Comment by terrified9** [comment]
forge moment

**Comment by ItCameFr0mMars** [comment]
you can dm Avankiter/Constructor and he can send u the mappings

**Comment by mikessx** [comment]
Someone figureout how to solve? I have the same problem

**Comment by Avanatiker** [comment]
I temporarily fixed it by reverting to the old build script.
