### ISSUE TITLE
Gradle building failed

### ISSUE THREAD

**Issue by Lqnz** [lambda-client/lambda-legacy#155]
**Describe the bug**
I tried building Lambda by basically doing the cmd way. and I got an error

**To Reproduce**
1. Download the source and extract it
2. Go to cmd and change directory
3. Do gradlew setupdecompworkspace
4. And once you do that, Just wait and see the error

**Debug info**
Here's the error I got: https://pastebin.com/RStqXGxy

**Comment by ToxicAven** [comment]
This is currently a known issue with forgegradle. We are currently looking for the cause of the issue and it should (hopefully) be resolved in the next few days.

**Comment by huddy987** [comment]
duplicate of https://github.com/lambda-client/lambda/issues/154
