### ISSUE TITLE
Surround is slow

### ISSUE THREAD

**Issue by Suollo** [lambda-client/lambda-legacy#160]
Compared to some other clients the surround feature is slow and this can be an issue for pvp. idk if you can do something about it but it would be cool.

**Comment by ItCameFr0mMars** [comment]
did you turn down the tick delay? I noticed the same issue even with this tweak

**Comment by badcodehash** [comment]
it is in fact remarkably terrible even on the lowest setting. It is not surround, it is slowround

**Comment by ItCameFr0mMars** [comment]
haha yeah

**Comment by Doogie13** [comment]
the problem is it cannot place more than 1 block per tick, so it is slow. it is, however, more reliable. if this was fixed it would be better than most atm

**Comment by badcodehash** [comment]
> the problem is it cannot place more than 1 block per tick, so it is slow. it is, however, more reliable. if this was fixed it would be better than most atm

maybe you mean more than one block per half a second? It is unbelievably slow.

**Comment by dudethis** [comment]
> > the problem is it cannot place more than 1 block per tick, so it is slow. it is, however, more reliable. if this was fixed it would be better than most atm
> 
> maybe you mean more than one block per half a second? It is unbelievably slow.

ye.. 1 block per tick would be fast asf on a normal server running at 20 ticks per second

**Comment by badcodehash** [comment]
Perhaps take inspiration from your dearest "friends" phobos and xulu. Their clients place 8 blocks (a full surround) in less than 0.25 seconds time.

**Comment by gvmii** [comment]
Why be rude? If you really want it, then just code it yourself, jesus.

**Comment by Suollo** [comment]
If you actually read the original suggestion you would see that I said it would be cool to see, I never said the devs had to do anything
