### ISSUE TITLE
Crashes on Pojavlauncher

### ISSUE THREAD

**Issue by liangforstudy** [lambda-client/lambda-legacy#164]
I'm not sure if the devs of lambda will ever support pojavlauncher, but here's my bug report anyway.

You can get pojavlauncher from the play store:
https://play.google.com/store/apps/details?id=net.kdt.pojavlaunch
Their GitHub: https://github.com/PojavLauncherTeam/PojavLauncher

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lambda (lambda)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.lambda.client.module.modules.misc.DiscordRPC

**Comment by liangforstudy** [comment]
[crash-2021-10-07_00.15.02-client.txt](https://github.com/lambda-client/lambda/files/7297826/crash-2021-10-07_00.15.02-client.txt)

**Comment by ToxicAven** [comment]
This is due to our DiscordRPC not supporting ARM.

**Comment by NepNep21** [comment]
The latest commit added ARM support, so you can try that, but it may not work on android, and if it doesn't, i don't think there is much we can reasonably do

**Comment by liangforstudy** [comment]
So, it will never support pojavlauncher? Or you need to make a build that is compatible with pojavlauncher by removing the DiscordRPC?

Edit: where can I find the latest commit? I'm new to GitHub.

**Comment by liangforstudy** [comment]
where can I find the latest commit? I'm new to GitHub.
This one? 
https://github.com/lambda-client/lambda/releases/tag/2.07.01
