### ISSUE TITLE
Devs get no bitches

### ISSUE THREAD

**Issue by Crystallinqq** [lambda-client/lambda-legacy#17]
**Describe the bug**

Devs get no bitches

**To Reproduce**

1. Say slightly mean word
2. Get muted in the discord

**Expected behavior**

Devs to get bitches

**Debug info**

N/A
**Additional context / media**

N/A

**Comment by Crystallinqq** [comment]
Fix ASAP

**Comment by Natan515** [comment]
Ah, be nicer next time and u won't be muted

**Comment by JohnShiozo** [comment]
lol
