### ISSUE TITLE
Things to do before release

### ISSUE THREAD

**Issue by czho** [lambda-client/lambda-legacy#171]
Please comment if you think something else should be added to this list. These things will be removed once added. 
Note: Alot of these should be done by release, but others may be a matter of opinion and may not get added or finished.

- [x] Outline in gui should have an option
- [ ] Antireconnectban module
- [x] Tooltips dont obay text color option
- [ ] Frame size doesn't save
- [ ] Hudelements are inconsistent, many have custom colors but others don't, also those text colors are inconsistent with the rest of the client as well
- [x] Needs better boatfly
- [x] Nametags has custom font option for some reason
- [ ] Make no modules use sliders for colors
- [ ] Esp wireframe mode
- [ ] Remove esp shadermode
- [ ] Hole esp gradient mode
- [ ] Crystalesp shit
- [ ] Chunksize causes your player model to stop rendering
- [x] Inventory hud uses kami blue colors
- [x] Remove antibot
- [ ] Add option to auto armor to not do stuff when in inventory gui
- [ ] Fix inconsistent spelling of armor and armour
- [ ] Add bypass mode for criticals
- [ ] Add mutliplace to surround
- [ ] Mob owner should work on all mobs
- [ ] Better scaffold
- [ ] Remount description should be changed to entity not horse
- [ ] Make jesus work again
- [ ] Fix bug with auto sprint and speed on
- [ ] Add weather to norender and remove antiweather
- [x] Remove automine
- [x] Remove color sign
- [x] Remove consoleSpam
- [x] Move antifog to norender
- [x] Move antioverlay to norender
- [x] Move armorhide to norender
- [x] Move clean gui to norender
- [x] Combine extratab and tab friends
- [ ] Make trajectories look less weird with bezier curves
- [ ] Make breadcrumbs look less weird with bezier curves
- [ ] Combine void esp, storageesp, and breaking esp into esp or change names because why tf are they named esp and not on esp
- [ ] Make antiforcelock better
- [x] Remove endteleport
- [ ] Add different timers for rubber band and lag in lag notifier
- [ ] Add higher limit in packet limiter
- [ ] Add all packets to packet logger 
- [ ] Put autotpa into chatplus 
- [ ] Combine friend highlight and tab friends
- [ ] Clickgui and GuiColors should be merged
- [x] Elytrafix should be added to main client
- [x] Plugin GUI move to ClickGUI
- [x] Update checker shouldn’t trigger for non release builds
- [x] Change GuiScale only on mouse release
- [ ] Fix issue with mob owner, with connection issues

**Comment by Avanatiker** [comment]
Lets see what we can tackle :)

**Comment by condem777** [comment]
Fix AutoEat's Pause baritone as it doesn't work

**Comment by condem777** [comment]
Fix changing module settings that cause the game to crash. One of them is AutoEject and there is others

**Comment by condem777** [comment]
And add a mend module for tools

**Comment by condem777** [comment]
And make Auto Tunnel Faster and HighwayTools

**Comment by condem777** [comment]
If possible add a module where you automatically place a shulker down clear its inventory and destroy it. It would be game changer for people who build massive schematics

**Comment by condem777** [comment]
Also Last thing i promise. Add Golden Apple to auto eat. So when your golden apple runs out then you can auto eat another one

**Comment by strunberg** [comment]
Could you please add the feature of Impact where it tells you the cords of both the nether & overworld?

![dffdfdfd](https://user-images.githubusercontent.com/6355904/139050394-9475c85d-149f-40d1-b3fa-3ff6ba88d3da.png)

**Comment by Doogie13** [comment]
why remove ESP shader mode? i like it

**Comment by czho** [comment]
> Could you please add the feature of Impact where it tells you the cords of both the nether & overworld?
> 
> 
> 
> ![dffdfdfd](https://user-images.githubusercontent.com/6355904/139050394-9475c85d-149f-40d1-b3fa-3ff6ba88d3da.png)
> 
> 
> 
> 
> 
> 

This is already In the client under coordinates, it's a hud module

**Comment by czho** [comment]
> Also Last thing i promise. Add Golden Apple to auto eat. So when your golden apple runs out then you can auto eat another one

good idea, this would be nice for pvping but also just not accidentally dying cause you are on fire

**Comment by strunberg** [comment]
> 
> 
> > Could you please add the feature of Impact where it tells you the cords of both the nether & overworld?
> > ![dffdfdfd](https://user-images.githubusercontent.com/6355904/139050394-9475c85d-149f-40d1-b3fa-3ff6ba88d3da.png)
> 
> This is already In the client under coordinates, it's a hud module

I didn't know that, thank you.

**Comment by ItCameFr0mMars** [comment]
Completed the norender merges and module deletions: https://github.com/lambda-client/lambda/pull/193
