### ISSUE TITLE
Autototem

### ISSUE THREAD

**Issue by ASOwnerYT** [lambda-client/lambda-legacy#172]
**Is your feature request related to a problem? Please describe.**
When my totem pops, even if I have another totem in my inventory it doesn't go into my offhand.

**Describe the solution you'd like**
AutoTotem would automatically put a totem in your offhand if the totem pops, like in Impact client.

**Comment by czho** [comment]
This is already in the client under AutoOffhand.

**Comment by ASOwnerYT** [comment]
Oh thanks! I didn't see that. It would be nice to add a feature where if you search 'Autototem' in the click GUI, it shows AutoOffhand.
