### ISSUE TITLE
Error when launching game from client jar built from the source code

### ISSUE THREAD

**Issue by ASOwnerYT** [lambda-client/lambda-legacy#175]
**Describe the bug**
I built the client as a jar as per the build instructions, but when I launch the game using the Forge profile in the official Minecraft launcher, I get the following crash error:
```
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lambda (lambda)
Exit Code: 255
```
[Full crash log](https://pastebin.com/a5fySce2)

**To Reproduce**

1. Build the final client JAR as per the build instructions in the readme
2. Put it in the mods folder in the .minecraft folder
3. Launch Forge 1.12.2 in the official Minecraft launcher
4. The client launches and starts loading, but crashes and shows the error before it can finish loading

**Expected behavior**

I would be able to build the client jar myself from the latest source code and use it (expecting some bugs, of course, but I would like it to be usable)

**Debug info**

I'm not able to get past the loading screen on my version built directly from the latest source code.

**Additional context / media**

**Comment by Avanatiker** [comment]
Its because you compiled it with a wrong java version. Make sure to select Java 1.8 everywhere!

**Comment by terrified9** [comment]
use java 8 to compile

**Comment by ASOwnerYT** [comment]
Oh thanks! I thought it was already using Java 8 and I forgot to check.
