### ISSUE TITLE
 Unable to locate a logging implementation

### ISSUE THREAD

**Issue by emyfops** [lambda-client/lambda-legacy#180]
**Describe the bug**
ERROR StatusLogger Unable to locate a logging implementation, using SimpleLogger

**To Reproduce**

1. Do the steps to install lambda
3. ./gradlew build
`ERROR StatusLogger Unable to locate a logging implementation, using SimpleLogger
Note: SpongePowered MIXIN Annotation Processor Version=0.8.2 (MixinGradle Version=0.7)
Note: ObfuscationServiceMCP supports type: "notch"
Note: ObfuscationServiceFG3 supports type: "searge"
Note: Loading searge mappings from C:\Users\Administrator\Desktop\lambda\build\createMcpToSrg\output.tsrg
Note: Writing refmap to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-refmap.json
Note: Writing refmap to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-refmap.json
Note: Writing searge composite mappings to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-mappings.tsrg
Note: Writing refmap to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-refmap.json
Note: Writing refmap to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-refmap.json
Note: Writing searge composite mappings to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-mappings.tsrg`

**Expected behavior**
Build Successful

**Comment by NepNep21** [comment]
That doesn't look like a fatal error to me, please send the whole log (from entering the command to the bottom of the terminal) if a jar doesn't exist at build/libs/

**Comment by emyfops** [comment]
> That doesn't look like a fatal error to me, please send the whole log (from entering the command to the bottom of the terminal) if a jar doesn't exist at build/libs/

It does build the jar, unfortunately, when forge load it (1.12.2) it instantly crashed

**Comment by NepNep21** [comment]
In that case paste <MINECRAFT_DIR>/logs/latest.log to https://paste.ee and post the link here

**Comment by emyfops** [comment]
https://paste.ee/p/vel51#nc4tPtyvDngMMKIvpBfoBL3Hv29SUacN

> In that case paste <MINECRAFT_DIR>/logs/latest.log to https://paste.ee and post the link here

**Comment by NepNep21** [comment]
That issue is caused by compiling lambda with java 9+, compile it with java 8 and it should work

**Comment by emyfops** [comment]
Using JDK 8, now the game crashes instantly
https://paste.ee/p/FbwKq#WJREBzOSHbeM5rX6T5axNTfz7zyaENZO

**Comment by NepNep21** [comment]
Interesting, that's the same issue from the actions builds, but it's the first time I'm seeing it outside of them, no idea how to fix it

**Comment by emyfops** [comment]
This is the output i have
```

20:18:33: Executing tasks ':classes :testClasses'...

Starting Gradle Daemon...
Gradle Daemon started in 2 s 777 ms

> Configure project :
[MixinGradle] Skipping eclipse integration, extension not found

> Task :downloadMcpConfig
> Task :extractSrg UP-TO-DATE
> Task :createMcpToSrg UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :compileKotlin

> Task :compileJava
ERROR StatusLogger Unable to locate a logging implementation, using SimpleLogger
Note: SpongePowered MIXIN Annotation Processor Version=0.8.2 (MixinGradle Version=0.7)
Note: ObfuscationServiceMCP supports type: "notch"
Note: ObfuscationServiceFG3 supports type: "searge"
Note: Loading searge mappings from C:\Users\Administrator\Desktop\lambda\build\createMcpToSrg\output.tsrg
Note: Writing refmap to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-refmap.json
Note: Writing refmap to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-refmap.json
Note: Writing searge composite mappings to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-mappings.tsrg
Note: Writing refmap to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-refmap.json
Note: Writing refmap to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-refmap.json
Note: Writing searge composite mappings to C:\Users\Administrator\Desktop\lambda\build\tmp\compileJava\compileJava-mappings.tsrg

> Task :classes
> Task :compileTestKotlin NO-SOURCE
> Task :compileTestJava NO-SOURCE
> Task :testClasses UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 14s
6 actionable tasks: 3 executed, 3 up-to-date
20:20:50: Tasks execution finished ':classes :testClasses'.
```

> Interesting, that's the same issue from the actions builds, but it's the first time I'm seeing it outside of them, no idea how to fix it

**Comment by emyfops** [comment]
Oh and there is the crash log + latest.log 
Crash: https://paste.ee/p/2UvWv#CtlUXLRr9OBPKAN4s4a6lIxTckWhnzsL
latest: https://paste.ee/p/CMC68#ZiETfSZInM90sST3pTUxwQV4BJl1ai6T

**Comment by emyfops** [comment]
Issue closed, I contacted the maintainer and it looks like It's related to the mapping of ForgeGradle
