### ISSUE TITLE
StorageViewer

### ISSUE THREAD

**Issue by kozia132** [lambda-client/lambda-legacy#183]
Some kind of Storage Viewer to where when you look at storage it has some kind of GUI Element that shows whats in the storage container.

ex. If you look at a chest, there will be something that shows on-screen that shows whats in the chest, so you do not have to place it.

This is different from things like ContainerPreview because ContainerPreview works in the inventory, StorageViewer will work in the game itself, where you can move and look around.

**Comment by czho** [comment]
This is impossible without opening each chest, which kinda defeats the point when you could just yknow open the chest to see the contents. If you really want this, you could just use inventory walk, or in some other clients there is a module called silent close.

**Comment by Avanatiker** [comment]
It could cache the contents of a chest once opened and display it actually like in meteor

**Comment by SplatTab** [comment]
get shulkerviewer mod lmao

**Comment by strunberg** [comment]
> 
> 
> It could cache the contents of a chest once opened and display it actually like in meteor

Sounds like the correct move. After all only you have access to a echest.
