### ISSUE TITLE
Lambda after some time didnt work

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#184]
I was playing today and yesterday and after few hours labda just stopped working elytra fly works but everything else no. This is my problem or what?

**Comment by ToxicAven** [comment]
Send logs please.

**Comment by ghost** [comment]
[latest.log](https://github.com/lambda-client/lambda/files/7529191/latest.log)

**Comment by ghost** [comment]
i love lambda client so much so if you can help that would be nice

**Comment by ghost** [comment]
im using 2 plugins highway tools and 5b5t dupe maybe this is a problem im not sure

**Comment by Avanatiker** [comment]
Please describe your problem more precise. What exactly does not work

**Comment by ghost** [comment]
> Please describe your problem more precise. What exactly does not work

so for example im playing 5b5t and i im afk for 10 -20 minutes and when im getting back lambda not working.
then works only blink and eltra fly module nothing else
and when im using command ";baritone goto 0 0" or someonething like that it just crashing

now works cause i reinstalled forge and i deleted lambda folder but i had already 1 crash

**Comment by ghost** [comment]
again i was afk on main screen for 40 mins and lambda stop working
