### ISSUE TITLE
lamda crashing with w+3

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#186]
im using w+3 and lambda and that crashing

**Comment by ToxicAven** [comment]
Please post a log so we can attempt to fix this incompatibility.

**Comment by Keplerqq** [comment]
> Please post a log so we can attempt to fix this incompatibility.
[latest.log](https://github.com/lambda-client/lambda/files/7532830/latest.log)

**Comment by ToxicAven** [comment]
Why are you using Postman, W+3 and Lambda? All this does is create incompatibilities.

**Comment by ghost** [comment]
> Why are you using Postman, W+3 and Lambda? All this does is create incompatibilities.

w + 3 crystal aura is good for spamming so im using it as a second pvp client i just deleted postman and its fine
