### ISSUE TITLE
build issue with intellji

### ISSUE THREAD

**Issue by master7720** [lambda-client/lambda-legacy#188]
when i build the client in intellji and open libs it just gives me a ton of groovy jars

**Comment by ToxicAven** [comment]
please provide a log in the future when making bug reports.

**Comment by master7720** [comment]
What log?

**Comment by ToxicAven** [comment]
When attempting to build, IntelliJ should open a window at the bottom of your screen. Please make sure that you have read the https://github.com/lambda-client/lambda#contributing section of our readme.

**Comment by master7720** [comment]
i did.

**Comment by master7720** [comment]
do it so you can build it with CMD :/

**Comment by ToxicAven** [comment]
WSL or git-bash is required for building on windows. https://git-scm.com/download/windows
