### ISSUE TITLE
Auto Chorus fruit

### ISSUE THREAD

**Issue by strunberg** [lambda-client/lambda-legacy#189]
It would be nice if you could toggle a plugin that would automatically eat Chorus fruit if you're close to drowning, in Laval, or trapped in sand or gravel.

**Comment by ItCameFr0mMars** [comment]
Would it be appropriate to put it in the autolog module?

**Comment by strunberg** [comment]
> autolog module?
As in teleport and then auto log out?

**Comment by Avanatiker** [comment]
Maybe add it to autoeat?

**Comment by ItCameFr0mMars** [comment]
> > autolog module?
> > As in teleport and then auto log out?

well maybe have an option to log out? I'll start working on it

**Comment by mmvanheusden** [comment]
make it smart, if the player is still in danger after the chorus teleport, log the player out

**Comment by ToxicAven** [comment]
Just adding chorus fruit to autoeat would work fine. Health delay, and autolog exists for a reason, we don't need to add a whole new module for this.
