### ISSUE TITLE
[Help] Where is the documentation for the Lambda API?

### ISSUE THREAD

**Issue by Node-Kid** [lambda-client/lambda-legacy#191]
I've recently been wanting to try out the Lambda API, but could not find any documentation besides already created modules. Can someone point me in the right direction or tell me if there is not any documentation?

Thanks in advance,
Node-Kid

**Comment by czho** [comment]
I’m sorry, there is currently no documentation on that, because the only thing it is really used for, is the plug-in sdk. If you have any questions tho feel free to ask on the discord:  https://discord.gg/KTH4XBmp

**Comment by Avanatiker** [comment]
When you want to code something just think about what parts of it are already existing in the mod and then check the code out
