### ISSUE TITLE
Autoobsidian issues !12$XMR reward!

### ISSUE THREAD

**Issue by SavexG** [lambda-client/lambda-legacy#200]
1.)

Here you can see the main issue with Autoobsidian it takes way longer to mine echests with autoobsidian then with vanilla mining on 2b2t

https://youtu.be/wNUmgPn3IwM

2.)

Autoobsidian disables itself when it hits a shulker box where no echests are in it even though there were still many shulkers with lots of echests in the inventory

Recommendation:
make it so Autoobsidians search shulker ignores shulkers with no echests in them and only disables itself after there is no more shulker with echests or echests in the inventory. (it's possible to see contents of shulkers with container preview)

https://youtu.be/QfLT3vMgPAo

__________________________________________________________________________________________________________

the following settings were used in the videos 

![2021-12-13_17-35](https://user-images.githubusercontent.com/65229679/145854050-57dc4d25-bb95-4826-a0b4-877705048494.png)

for any further question or just casual talk about the issues msg Save___G#4444 on discord I can also take some time and explain it again in a screenshare vc 

to claim the reward, make a commit that fixes all of the issues above and introduces no new bugs and has perfect compatibility with Highwaytools after 1 or 2 days of testing msg Save___G#4444 on discord and you will be rewarded.

! BONUS ! if you get instantbreak to work again +5$ in xmr 

Disclamer: 
you will get the exchange rate of XMR to $ at the time the transaction will be sent NOT the one from 13.Dec.2021

the cryptocurrency reward is just as a little bonus and shouldn't be seen as a way of compensation for the time and effort put into this
it's a voluntary project.

**Comment by mmvanheusden** [comment]
4ANh9ZPun4iNtHX1XSXgeGhvfJMpaV7XbSJa42WpzJNfYs8q21VocEpGbYeLpaZyz98a62oJzFzxBdoMo2eDmNzrDM8QZGm


:trollface:

**Comment by ToxicAven** [comment]
Has this been solved by the merged PR?
@SavexG

**Comment by SavexG** [comment]
> Has this been solved by the merged PR? @SavexG

I'll checkt it out when I'm home since when is the fix in the nightly?

**Comment by ToxicAven** [comment]
> > Has this been solved by the merged PR? @SavexG
> 
> I'll checkt it out when I'm home since when is the fix in the nightly?

Since before 3.0, it is in the stable release.

**Comment by SavexG** [comment]
> > > Has this been solved by the merged PR? @SavexG
> > 
> > I'll checkt it out when I'm home since when is the fix in the nightly?
> 
> Since before 3.0, it is in the stable release.
> 

Oh yeah i remember again CZ fixed the 1) issue but not the 2nd one.
But the 2nd issue isn't relevant anymore since hwt now runs with its own storage management. 
So I asked CZ for his address but he declined and didn't want to accept it.
Now I'm thinking about keeping this up as a bounty to get instant mine to work again but this seems kinda unlikely from what constructor told me so I'm up for any suggestions what to do with the leftover XMR from this issue.

**Comment by mmvanheusden** [comment]
make like a highway building tournament or something and the winner gets the reward

**Comment by mmvanheusden** [comment]
or give it to me :troll: 

4ANh9ZPun4iNtHX1XSXgeGhvfJMpaV7XbSJa42WpzJNfYs8q21VocEpGbYeLpaZyz98a62oJzFzxBdoMo2eDmNzrDM8QZGm

**Comment by ToxicAven** [comment]
Closing as this appears to have become stable.
