### ISSUE TITLE
Hot-reloading with intellij

### ISSUE THREAD

**Issue by mmvanheusden** [lambda-client/lambda-legacy#204]
Hi, is it possible to hot-reload the client with intellij idea?

i've already tried this: https://gist.github.com/quat1024/8bf436c85e5c140d27d49a7dc6c09982
but it completely breaks the whole project.

is it possible? and how?

**Comment by NepNep21** [comment]
Works fine for me by just clicking the build button and saying yes to the popup when in a debug run, with no extra configuration required, not sure what the issue is for you

**Comment by mmvanheusden** [comment]
bruh how did i miss that


thanks for the help
