### ISSUE TITLE
Gui Issue

### ISSUE THREAD

**Issue by ors0** [lambda-client/lambda-legacy#214]
Under the names of the modules of the point, it is very annoying 
![unknown (1)](https://user-images.githubusercontent.com/92330352/147834228-41f785a2-b829-425f-a51b-318a9c89dfcb.png)
here are my settings for the gui
![image](https://user-images.githubusercontent.com/92330352/147834415-708df609-a368-4c37-96ae-62d72e225b3e.png)

**Comment by huddy987** [comment]
I don’t see any issue, what’s the problem?

**Comment by ors0** [comment]
Look closely, under the names of the modules of the point, it is very annoying

**Comment by floorshame** [comment]
> I don’t see any issue, what’s the problem?

There Are Small Dots Underneath The Text

**Comment by floorshame** [comment]
Try And Turn Off Custom Font, Or Try Using Another Font
