### ISSUE TITLE
cant open worlds or servers 

### ISSUE THREAD

**Issue by ustrux** [lambda-client/lambda-legacy#215]
recently I enabled the stop all packets mod and this therefore not letting me load servers or worlds to turn this setting off. I cant open the GUI to disable this because I cant open worlds or servers and I cant open it in menu

**Comment by NepNep21** [comment]
Change it in the config file, i don't remember where exactly it is but you can figure it out by looking in the lambda/ directory

**Comment by huddy987** [comment]
Just delete the config file
