### ISSUE TITLE
GUI scale change

### ISSUE THREAD

**Issue by Avanatiker** [lambda-client/lambda-legacy#22]
When rescaling GUI it should wait until user let the slider go and after this resize the elements

**Comment by ToxicAven** [comment]
https://github.com/lambda-client/lambda/blob/4396adf9ce1fec325002e32a144b7659f3fcd699/src/main/kotlin/com/lambda/client/module/modules/client/ClickGUI.kt#L57

This appears to have been added previously without the issue being closed.
