### ISSUE TITLE
mod crashes as soon as launch

### ISSUE THREAD

**Issue by akgamextreme** [lambda-client/lambda-legacy#221]
**Describe the bug**

The game crashed whilst initializing game
Error: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.SecurityException: class "javax.annotation.Nullable"'s signer information does not match signer information of other classes in the same package
Exit Code: -1

**To Reproduce**

launch ig

**Expected behavior**

the client launched and let me play on 9b9t
**Debug info**

wat
**Additional context / media**
[crash-2022-01-03_19.20.02-client.txt](https://github.com/lambda-client/lambda/files/7802216/crash-2022-01-03_19.20.02-client.txt)

**Comment by NepNep21** [comment]
Future issue, try https://github.com/lambda-client/lambda/suites/4811747896/artifacts/135400180

**Comment by akgamextreme** [comment]
o ok

**Comment by itsmaybetokyo** [comment]
I'm having this problem https://prnt.sc/25upr7p
It's a custom font problem

**Comment by huddy987** [comment]
@2b2tplayer please create a new issue

closing this issue as it’s related to a future incompatibility that is now fixed
