### ISSUE TITLE
Stacked minecart chest finder

### ISSUE THREAD

**Issue by MP3Martin** [lambda-client/lambda-legacy#228]
**Is your feature request related to a problem? Please describe.**
No problem here.

**Describe the solution you'd like**
Multi minecart chest finder. The module will show tracer to it and notify you. It will find if there are two or more minecart chests in one block.
**Describe alternatives you've considered**
None. This will make more people use lambda.

**Additional context**
`return None`

**Comment by ToxicAven** [comment]
How would this be useful exactly? and when would this happen?

**Comment by MP3Martin** [comment]
> How would this be useful exactly? and when would this happen?

It will be good to find stashes that are normally unnoticeable, because the minecarts are in one block.

It will simply highlight 2 or more minecarts in one block right when it enters your render distance.

**Comment by ToxicAven** [comment]
This is such a ridiculous and niche use case that it isn't worth wasting time trying to make it.
