### ISSUE TITLE
Add EntityControl

### ISSUE THREAD

**Issue by gvmii** [lambda-client/lambda-legacy#230]
**Is your feature request related to a problem? Please describe.**

When I get a Horse, I cannot use it without a Saddle, and that makes me sad :(
**Describe the solution you'd like**

Add EntityControl so I can ride it without a Saddle

**Describe alternatives you've considered**

Make entityspeed not rubberband you when controlling a horse and going up a block

**Additional context**

**Comment by Avanatiker** [comment]
EntityControl is in EntitySpeed
