### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by keirman1** [lambda-client/lambda-legacy#232]
**Describe the bug**
The game crashes once it opens the main menu

**To Reproduce**
idk just use the mods i use 

**Expected behavior**
for it to work

**Additional context / media**
![image](https://user-images.githubusercontent.com/80916044/151837374-b08e04fd-7d5a-4a86-8700-a58184ced034.png)
those are the clients i use also asdaware is a salhack skid

**Comment by NepNep21** [comment]
Not enough information, send logs/latest.log with https://paste.ee

**Comment by keirman1** [comment]
ok

**Comment by keirman1** [comment]
https://paste.ee/p/YBOuQ

**Comment by keirman1** [comment]
oh ok thanks
