### ISSUE TITLE
Crystal pvp is slow.

### ISSUE THREAD

**Issue by jade0101hedenskog** [lambda-client/lambda-legacy#240]
On 2b2t anticheat cheat it places slow and breaks slow. Test on 2b2tpvp.org its the same problem is on most other free pvp clients.
If Anyone found a free pvp client wich can bypass. Respond with its name pls: or if you found a work around with other modules, or i'm just dum at setting up a config tell me.

Example: Wurste +3

**Comment by ToxicAven** [comment]
Use the default config on most servers.

**Comment by mmvanheusden** [comment]
Speed also depends on your ping and 2b also limits crystal placing speed i thing

**Comment by ToxicAven** [comment]
Yep. It's all about driving a config and working around the anticheat. None of the lead dev team PVP's on 2b2t, so we cannot provide a proper config.

**Comment by master7720** [comment]
> On 2b2t anticheat cheat it places slow and breaks slow. Test on 2b2tpvp.org its the same problem is on most other free pvp clients. If Anyone found a free pvp client wich can bypass. Respond with its name pls: or if you found a work around with other modules, or i'm just dum at setting up a config tell me.
> 
> Example: Wurste +3

NO REALLY 2B? CPVP IS SLOW OMG ITS LIKE ITS STRICT

**Comment by ToxicAven** [comment]
This is getting offtopic now.
