### ISSUE TITLE
Forgelin X Lambda compatibility issue

### ISSUE THREAD

**Issue by DanDucky** [lambda-client/lambda-legacy#242]
So forgelin (https://github.com/shadowfacts/Forgelin)
```
Additions

    Shades the Kotlin standard library, runtime, coroutines-core, and reflect libraries so you don't have to.
    Provides a Forge ILanguageAdapter for using Kotlin object classes as your main mod class.
```
Is required to run another Kotlin mod, Better Foliage. But launching Forgelin and Lambda doesn't work together. Below is my crash report.
[crash-2022-02-21_14.19.18-client.txt](https://github.com/lambda-client/lambda/files/8112783/crash-2022-02-21_14.19.18-client.txt)

P.S. if it's any help, the same issue persists with Kami Blue

**Comment by ToxicAven** [comment]
Unless Lambda switches to using Forgelin (Which was discussed by the Kami Blue devs if I recall correctly), there isn't much we can do about this. Adding an extra mod to use a mod is unnecessary, even at the cost of a large jar. We can't really assist with this, or try to fix the incompatibility.

**Comment by DanDucky** [comment]
3:
now I'm crying about it. thx for the response tho <3

**Comment by ToxicAven** [comment]
Sorry we can't do anything about it for the time being. We'll keep this in mind moving forward, if there is some way to simply correct it, we will attempt to do so.
