### ISSUE TITLE
AutoGrief

### ISSUE THREAD

**Issue by KassuK1** [lambda-client/lambda-legacy#255]
Basically AutoGrief it would automatically grief an selected area with the optimal amount of TNT using baritone or something else like that and maybe a few different modes one that would destroy it completely one that would leave ruins behind.

**Comment by a-a-afk** [comment]
these steps may seem complex at first, but here it goes...
1. right click with tnt in hand

**Comment by ItCameFr0mMars** [comment]
scaffold tnt

**Comment by mmvanheusden** [comment]
> scaffold tnt

lambdas scaffold works so good!!1!1!1

**Comment by a-a-afk** [comment]
Atleast its better than kb's

**Comment by ItCameFr0mMars** [comment]
there is a new scaffold in the works btw. Check out pulls if you want to get it btw
