### ISSUE TITLE
Player entity disappears in f5

### ISSUE THREAD

**Issue by ItsTact** [lambda-client/lambda-legacy#262]
![2022-03-05_18 58 21](https://user-images.githubusercontent.com/69988786/156903630-29a022ce-675d-4fcb-8269-eff57158dd52.png)

**Comment by mmvanheusden** [comment]
Disable chunk size hud element or make the refresh delay higher

**Comment by RexBluefox** [comment]
> Disable chunk size hud element or make the refresh delay higher

had the same issue. this works

**Comment by ToxicAven** [comment]
No template or follow up responses were given.
