### ISSUE TITLE
Removal of unnecessary clutter in the StashLogger module

### ISSUE THREAD

**Issue by gamerpaddy** [lambda-client/lambda-legacy#264]
**Is your feature request related to a problem? Please describe.**
when stashlogger finds for example a shulker, it logs that it found 0 droppers, 0 hoppers, 0 chests and x shulkers.

**Describe the solution you'd like**
dont log things that havent been found. only log x shulkers in the example above.

**Comment by Mathrandom7910** [comment]
what's up with you and stash finders

**Comment by mmvanheusden** [comment]
instead of opening 10 issues you could spend your time learning to code instead and open pull requests 👍

**Comment by huddy987** [comment]
Thank you for your contribution!
