### ISSUE TITLE
pause AutoWalk when pressing S (or W when going backwards)

### ISSUE THREAD

**Issue by gamerpaddy** [lambda-client/lambda-legacy#266]
**Is your feature request related to a problem? Please describe.**
autowalk doesnt pause unless i deactivate it.

**Describe the solution you'd like**
pause autowalk when pressing the key of opposite direction.
resume when key is released.

**Comment by mmvanheusden** [comment]
Sure, will try to make that a reality

**Comment by mmvanheusden** [comment]
Fixed in pull request #271 

you can download the beta jar here: https://github.com/lambda-client/lambda/runs/5451183838
