### ISSUE TITLE
konas compability

### ISSUE THREAD

**Issue by rolkoztm** [lambda-client/lambda-legacy#275]
When konas compability fix???????????????

**Comment by Luigit12** [comment]
Rename lambda jar to "an.jar", worked for me.

**Comment by ToxicAven** [comment]
Renaming the jar to have an ! In the front, ex. `!lambda.jar` will fix this. This is because of Konas loading first, while having outdated dependencies.

**Comment by Doogie13** [comment]
cool letter k

**Comment by Luigit12** [comment]
> 

For some reason that didnt work for me, dont know why.

**Comment by rolkoztm** [comment]
ye it doesnt work help me:(
