### ISSUE TITLE
konas compability

### ISSUE THREAD

**Issue by rolkoztm** [lambda-client/lambda-legacy#276]
it doesnt work, renamed lambada to !lambada.jar and still dont work so help me

**Comment by ToxicAven** [comment]
Please send `.minecraft/logs/latest.log`

**Comment by rolkoztm** [comment]
> Please send `.minecraft/logs/latest.log`
[latest.log](https://github.com/lambda-client/lambda/files/8284840/latest.log)

**Comment by ToxicAven** [comment]
While it is not the direct issue, Lambda requires forge `14.23.5.2860`.

Try removing autobot or rusherhack and seeing if that fixes launching, normally Konas will work with lambda.

**Comment by rolkoztm** [comment]
i think its bcuz of autobot because autobot is old so anyway thanks

**Comment by rolkoztm** [comment]
removed both and it still dont work

**Comment by ToxicAven** [comment]
Resend a log with only Konas and lambda

**Comment by rolkoztm** [comment]
[latest.log](https://github.com/lambda-client/lambda/files/8287047/latest.log)

**Comment by ToxicAven** [comment]
Please send a list of all mods in .minecraft/mods, including subfolders. also you are still using forge 2855, you need forge 2860.

**Comment by rolkoztm** [comment]
> Please send a list of all mods in .minecraft/mods, including subfolders. also you are still using forge 2855, you need forge 2860.

i use only ONLY konas  +  lambada

**Comment by ToxicAven** [comment]
That is not what the logs show. Not just utility mods, all mods in use.

**Comment by master7720** [comment]
why use konas in the first place.waste of money.

**Comment by rolkoztm** [comment]
LMAOO forge update fixed everything thanks<3
