### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by rolkoztm** [lambda-client/lambda-legacy#277]
how to fix it ? ![image](https://user-images.githubusercontent.com/60612933/159055147-a20a2c2d-48ee-4107-8cf2-73ae09540e19.png)

**Comment by rolkoztm** [comment]
![image](https://user-images.githubusercontent.com/60612933/159055452-0c360267-739d-4864-b0aa-c5e8bab7c6c1.png)
i think nothing from addons is working

**Comment by ToxicAven** [comment]
This is due to an incompatibility with plugins made before the release of Lambda 3.1. They are in the process of being updated and will be released shortly.
