### ISSUE TITLE
Crash when using elytra

### ISSUE THREAD

**Issue by NovaProtocol** [lambda-client/lambda-legacy#278]
**Describe the bug**
When using elytra, it crashes a lot. If you used elytraflight with contol and land, it crash. If you tried elytra control with no easy take off and tried to fly, it crash, and so on. It's also pretty inconsistent. Some times crashing with just jumping while elytraflight is on.

Also, elytraflight's easy takeoff is kinda weird above chests. It's slowing down movement speed as if it's triggering the easy take off but since there's not enough height, it fails. Not my main report though.

Update: Works in  single player survival flawlessly.

I think it's related to the client failing to open elytra due to lag since it works in survival and i noticed that it only crashes when it tries to rubberband you back since server side you failled to open elytra but client side it's opened

**To Reproduce**
1. Turn on elytra flight.
2. Turn off easy take off
3. fly

This would probably work on your side. Just asking for help on why it crashes on my side.

**Expected behavior**
In theory, it would just work. I tried inertia's elytra flight and it works. Not sure why it doesn't for lamba or kami

**Debug info**
![image](https://user-images.githubusercontent.com/35219142/159133546-ee990bda-df0e-4806-b65c-1b0e2fa88220.png)

**Additional context / media**
I can record a video on request.

[crash-2022-03-20_02.10.51-client.txt](https://github.com/lambda-client/lambda/files/8309855/crash-2022-03-20_02.10.51-client.txt)

**Comment by ToxicAven** [comment]
We do not support Tlauncher use, and will not provide support to games using it.
