### ISSUE TITLE
Costum generated plugin crash

### ISSUE THREAD

**Issue by cheyao** [lambda-client/lambda-legacy#279]
**Describe the bug**
Crash when using self generated plugins

**To Reproduce**

1. Self generate highwayTools
2. Use it in mc
3. Crash

**Expected behavior**
Run HighwayTools

**Debug info**
[crash-2022-03-21_15.13.27-client.txt](https://github.com/lambda-client/lambda/files/8316134/crash-2022-03-21_15.13.27-client.txt)

**Comment by mmvanheusden** [comment]
try gradle build task jar

dont use grade build but gradle jar

**Comment by cheyao** [comment]
@mmvanheusden 
> try gradle build task jar
> 
> dont use grade build but gradle jar

Yes i used the jar (Gradle HighwayTools>Build>Jar)

**Comment by mmvanheusden** [comment]
> @mmvanheusden 
> > try gradle build task jar
> > 
> > dont use grade build but gradle jar
> 
> Yes i used the jar (Gradle HighwayTools>Build>Jar)

hmm then it is the opposite i forgor 💀 try gradle build

**Comment by cheyao** [comment]
Oh yea thx 
@mmvanheusden
