### ISSUE TITLE
AUTOEAT GOLDEN CARROTS

### ISSUE THREAD

**Issue by Cannabutter** [lambda-client/lambda-legacy#283]
Using auto-eat on Lambda only has the options of eating Golden Apples, Enchanted Golden Apples, while all other food is grouped 
together. Making it harder to conserve Golden Apples for PVP when you're out doing PVE and solo adventuring or mining Diamonds

If someone added the option of eating Golden Carrots you could use Golden Carrots a lot more frequently 
since auto farming Carrots is a breeze and Gold can be mined by the Boat loads

The only alternatives to this is either knowing how to dupe Golden Apples, 
spending time farming Apples (which we all know is the worst) 
or spending endless hours looting dungeon Chests. 

ps.
Please Help

**Comment by ghost** [comment]
AFAIK auto eat just eats the first food it finds in your hotbar. Just put your carrots in your hotbar while not in a pvp area and you are fine :)
