### ISSUE TITLE
Hide Unsupported Plugins From In-Game Downloader

### ISSUE THREAD

**Issue by huddy987** [lambda-client/lambda-legacy#289]
Unsupported plugins should be hidden from the in game downloader. Right now, some users are confused because they can download out of date plugins but then they get a bunch of warnings because the plugin is not pulled up to the latest API version.

For example, ChatPlus is not pulled up to the latest API version:
<img width="494" alt="Screen Shot 2022-04-05 at 9 55 53 AM" src="https://user-images.githubusercontent.com/35442144/161795907-d23bccfa-f082-47ed-b8dc-bfae795ae5af.png">

**Comment by Luigit12** [comment]
Maybe give them another colour or something

**Comment by syrenaaa** [comment]
isn't this checked here?
https://github.com/lambda-client/lambda/blob/c8ca60a8264a5d3bafcc4fef23250aa18aa609f6/src/main/kotlin/com/lambda/client/plugin/PluginManager.kt#L77

**Comment by Avanatiker** [comment]
yea

**Comment by syrenaaa** [comment]
so close?
