### ISSUE TITLE
AutoEZ

### ISSUE THREAD

**Issue by Luigit12** [lambda-client/lambda-legacy#294]
**Describe the bug**
The module AutoEz is not working at all

**To Reproduce**
Enable autoEz, kill someone -> no message in chat

**Expected behavior**
Should sent a message in chat right?

**Debug info**
How can I make a screenshot of something not happening :/

**Additional context / media**
a

**Comment by a-a-afk** [comment]
you dont take a ss, you record a video

**Comment by ToxicAven** [comment]
Using combat modules from other clients will result in our AutoEZ not marking people as targeted by you.
