### ISSUE TITLE
AutoEat doesn't work well with the combat modules

### ISSUE THREAD

**Issue by SnivyLlama** [lambda-client/lambda-legacy#296]
**Describe the bug**
Any time AutoEat triggers, the CA/KA/Surround always starts to bug out, and sometimes, the eating glitch occurs where it forever tries to eat one gap, probably because of the interference from the other modules

**To Reproduce**

1. Use KA/CA/Surround
2. Make sure the module is actively working
3. Drop your health below the health threshold OR just turn on Auto Eat once that happens
4. It should bug out most of the time

**Expected behavior**
The AutoEat works its buisness and doesnt interfere with the combat module, or stops if something else (like Surround) has more importance

**Debug info**
![Screenshot from 2022-04-15 21-19-52](https://user-images.githubusercontent.com/61280616/163657840-f78b154a-45ac-4795-af55-3b60a79b605c.png)

**Additional context / media**

**Comment by ToxicAven** [comment]
Most of the combat modules have a pause autoeat setting, which should fix this issue.
