### ISSUE TITLE
Optifine throws tons of errors

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#297]
Using: Optifine 1.12 and Lambda 3.1 on Forge with MultiMC

Log:  [latest.log](https://github.com/lambda-client/lambda/files/8500417/latest.log)

Problem:
Ok, so maybe it's not compatible with OF and I missed this, but otherwise: I get a HUGE amount of errors spamming my live log (As can be seen in the file above), and chat also giving a GL error every 10 seconds or so. I practically have to use optifine as my pc would just die trying to run 2b2t on it otherwise, and it's rather frustrating. From what I've heard and read, this client sounds absolutely awesome, but if I can't get it to work, I may have to drop back to Impact, which I don't think ElytraFly even works well on. I would appreciate support ASAP, but no pressure, as no way I'm going to be able to use it this session on 2b anyway lol. 

Thanks, and I hope you can fix this/give me info!

**Comment by mmvanheusden** [comment]
If you don't experience issues other than your chat being spammed with errors, you can safely disable "display errors" in your optifine settings

**Comment by ghost** [comment]
K. I just don't want things to go wrong, and if I have no clue what it does, I ask! LOL thanks for the advice.

**Comment by TudbuT** [comment]
> If you don't experience issues other than your chat being spammed with errors, you can safely disable "display errors" in your optifine settings

This is NOT how issues should be addressed. If it only happens when lambda is installed, there clearly is some issue. I made the mistake of handling issues on some of my projects like this and ended up with a buggy mess with no clue what was causing what.

**Comment by ghost** [comment]
Well, do you have any insight then? I can play without OF, it just sucks. I
got kicked for attempting to use Impact's elytrafly the other day, and if
lambda's works as well as anticipated, I'm pretty hyped to have a method of
travel other than entityspeed.

**Comment by ghost** [comment]
> > If you don't experience issues other than your chat being spammed with errors, you can safely disable "display errors" in your optifine settings
> 
> This is NOT how issues should be addressed. If it only happens when lambda is installed, there clearly is some issue. I made the mistake of handling issues on some of my projects like this and ended up with a buggy mess with no clue what was causing what.

Edit: Lambda itself just spams the error. I disabled OF and it does exactly the same thing as before. Unfortunately, I'm going to simply go back to horse travel for now, until this error is fixed. Possibly it has something to do with my SOC, but for now I'll just stick with Impact and optifine.

**Comment by ToxicAven** [comment]
Not enough info or logs have been provided to determine any actual issue here.
