### ISSUE TITLE
Tracers not working

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#300]
Tracers just create a tiny little line that doesn’t go to the middle of my screen, it just stays at the selected block. I wouldn’t even call that module tracers if it doesn’t work

**Comment by ToxicAven** [comment]
It sounds like you are using an incompatible mod. Could you send your mods list?

**Comment by ghost** [comment]
optifine, and i think Betterfows renderdistance

**Comment by ghost** [comment]
betterfps**

**Comment by ToxicAven** [comment]
Better fps is known to cause issues with many utility mods, check if the issues persist without it present.

**Comment by ghost** [comment]
Nvm I don’t have betterfps I just checked

**Comment by ghost** [comment]
Issue is still there though. Tracers do not fully go to the middle of my screen. Issue also happens with search module

**Comment by a-a-afk** [comment]
with lambda alone?

**Comment by BloodyNoah** [comment]
do you have some special render settings?

**Comment by ToxicAven** [comment]
This has been inactive, and similar issues have not been reported since.
