### ISSUE TITLE
crashes when entering the world

### ISSUE THREAD

**Issue by ARTERrs** [lambda-client/lambda-legacy#303]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Debug info**

**Additional context / media**

**Comment by NepNep21** [comment]
Not enough information, paste logs/latest.log to https://paste.ee and send the link here, though note that if you are pirating the game you will not get help

**Comment by ItCameFr0mMars** [comment]
homie submitted the template as an issue

**Comment by a-a-afk** [comment]
> homie submitted the template as an issue

not surprising

**Comment by Luigit12** [comment]
What server are you trying to join

**Comment by ToxicAven** [comment]
No information was provided.
