### ISSUE TITLE
Mobowner almost crashes the game when mob has an invalid UUID

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#306]
Title kinda explains it all. Somehow the game goes to literal seconds per frame upon rendering a mob with invalid UUID with "mobowner" enabled. Normal nametags work fine. Future nametags work fine. 
Disabling the mobowner thing instantly fixes it.

Server: 2b2t. Coords: available upon request for debug and not for murdering doggo. Discord: Robijntj3#1294

Screenshot of doggo:
![2022-05-05_15 08 24 - Copy](https://user-images.githubusercontent.com/101452146/167017567-99e540a6-1ba3-4897-bf3a-fd0867b2f242.png)

**Comment by mmvanheusden** [comment]
can you send any errors in your log? (enable show logs in the minecraft launcher)

**Comment by ghost** [comment]
> can you send any errors in your log? (enable show logs in the minecraft launcher)

Sorry for the late response, had to fly back. It throws a ton of the "response null" messages. Then a probably interesting bit. And then a ton of response null again. About 6 a second. 

Log below

`[Info: 2022-05-07 23:07:26.8310852: GameCallbacks.cpp(177)] Game/game () Info [01:07:26] [Client thread/ERROR] [Lambda]: Response is null or blank, internet might be down
[Info: 2022-05-07 23:07:27.0562399: GameCallbacks.cpp(177)] Game/game () Info [01:07:27] [Client thread/ERROR] [Lambda]: Response is null or blank, internet might be down
[Info: 2022-05-07 23:07:27.2241326: GameCallbacks.cpp(177)] Game/game () Info [01:07:27] [Client thread/ERROR] [Lambda]: Response is null or blank, internet might be down
[Info: 2022-05-07 23:07:27.3496072: GameCallbacks.cpp(177)] Game/game () Info [01:07:27] [Client thread/ERROR] [Lambda]: Failed requesting from Mojang API
[Info: 2022-05-07 23:07:27.3496631: GameCallbacks.cpp(177)] Game/game () Info java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/user/profiles/8f53681f62fe3bf19f154fdcadee93fc/names
[Info: 2022-05-07 23:07:27.3496834: GameCallbacks.cpp(177)] Game/game () Info at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3497004: GameCallbacks.cpp(177)] Game/game () Info at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3497171: GameCallbacks.cpp(177)] Game/game () Info at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3497342: GameCallbacks.cpp(177)] Game/game () Info at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3497512: GameCallbacks.cpp(177)] Game/game () Info at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3497675: GameCallbacks.cpp(177)] Game/game () Info at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3497835: GameCallbacks.cpp(177)] Game/game () Info at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3497993: GameCallbacks.cpp(177)] Game/game () Info at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3498223: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.commons.utils.ConnectionUtils.requestRawJsonFrom$lambda-1(ConnectionUtils.kt:14) ~[ConnectionUtils.class:?]
[Info: 2022-05-07 23:07:27.3498393: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.commons.utils.ConnectionUtils$$Lambda$1786/1378827648.invoke(Unknown Source) ~[?:?]
[Info: 2022-05-07 23:07:27.3498556: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.commons.utils.ConnectionUtils.runConnection(ConnectionUtils.kt:23) [ConnectionUtils.class:?]
[Info: 2022-05-07 23:07:27.3498715: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.commons.utils.ConnectionUtils.requestRawJsonFrom(ConnectionUtils.kt:10) [ConnectionUtils.class:?]
[Info: 2022-05-07 23:07:27.3498879: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.capeapi.AbstractUUIDManager.request(AbstractUUIDManager.kt:107) [AbstractUUIDManager.class:?]
[Info: 2022-05-07 23:07:27.3499052: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.capeapi.AbstractUUIDManager.requestProfileFromUUID(AbstractUUIDManager.kt:99) [AbstractUUIDManager.class:?]
[Info: 2022-05-07 23:07:27.3499235: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.capeapi.AbstractUUIDManager.requestProfile(AbstractUUIDManager.kt:75) [AbstractUUIDManager.class:?]
[Info: 2022-05-07 23:07:27.3499397: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.capeapi.AbstractUUIDManager.getOrRequest(AbstractUUIDManager.kt:70) [AbstractUUIDManager.class:?]
[Info: 2022-05-07 23:07:27.3499567: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.manager.managers.UUIDManager.getOrRequest(UUIDManager.kt:24) [UUIDManager.class:?]
[Info: 2022-05-07 23:07:27.3499734: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.capeapi.AbstractUUIDManager.getByUUID(AbstractUUIDManager.kt:35) [AbstractUUIDManager.class:?]
[Info: 2022-05-07 23:07:27.3499909: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.module.modules.render.MobOwner._init_$lambda-0(MobOwner.kt:33) [MobOwner.class:?]
[Info: 2022-05-07 23:07:27.3500128: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.module.modules.render.MobOwner$$Lambda$1183/1305270720.invoke(Unknown Source) [MobOwner.class:?]
[Info: 2022-05-07 23:07:27.3500334: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.util.threads.ThreadSafetyKt.safeListener$lambda-1(ThreadSafety.kt:26) [ThreadSafetyKt.class:?]
[Info: 2022-05-07 23:07:27.3500494: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.util.threads.ThreadSafetyKt$$Lambda$535/657504198.invoke(Unknown Source) [ThreadSafetyKt.class:?]
[Info: 2022-05-07 23:07:27.3500652: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.event.LambdaEventBus.invokeSerial(LambdaEventBus.kt:49) [LambdaEventBus.class:?]
[Info: 2022-05-07 23:07:27.3500808: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.event.LambdaEventBus.postProfiler(LambdaEventBus.kt:37) [LambdaEventBus.class:?]
[Info: 2022-05-07 23:07:27.3500965: GameCallbacks.cpp(177)] Game/game () Info at com.lambda.client.event.ForgeEventProcessor.onTick(ForgeEventProcessor.kt:38) [ForgeEventProcessor.class:?]
[Info: 2022-05-07 23:07:27.3501125: GameCallbacks.cpp(177)] Game/game () Info at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_32_ForgeEventProcessor_onTick_ClientTickEvent.invoke(.dynamic) [?:?]
[Info: 2022-05-07 23:07:27.3501284: GameCallbacks.cpp(177)] Game/game () Info at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
[Info: 2022-05-07 23:07:27.3501441: GameCallbacks.cpp(177)] Game/game () Info at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
[Info: 2022-05-07 23:07:27.3501606: GameCallbacks.cpp(177)] Game/game () Info at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349) [FMLCommonHandler.class:?]
[Info: 2022-05-07 23:07:27.3501767: GameCallbacks.cpp(177)] Game/game () Info at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911) [bib.class:?]
[Info: 2022-05-07 23:07:27.3501976: GameCallbacks.cpp(177)] Game/game () Info at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) [bib.class:?]
[Info: 2022-05-07 23:07:27.3502136: GameCallbacks.cpp(177)] Game/game () Info at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
[Info: 2022-05-07 23:07:27.3502295: GameCallbacks.cpp(177)] Game/game () Info at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
[Info: 2022-05-07 23:07:27.3502452: GameCallbacks.cpp(177)] Game/game () Info at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3502610: GameCallbacks.cpp(177)] Game/game () Info at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3502764: GameCallbacks.cpp(177)] Game/game () Info at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3503072: GameCallbacks.cpp(177)] Game/game () Info at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
[Info: 2022-05-07 23:07:27.3503240: GameCallbacks.cpp(177)] Game/game () Info at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[Info: 2022-05-07 23:07:27.3503399: GameCallbacks.cpp(177)] Game/game () Info at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[Info: 2022-05-07 23:07:27.3503597: GameCallbacks.cpp(177)] Game/game () Info [01:07:27] [Client thread/ERROR] [Lambda]: Response is null or blank, internet might be down
[Info: 2022-05-07 23:07:27.5487651: GameCallbacks.cpp(177)] Game/game () Info [01:07:27] [Client thread/ERROR] [Lambda]: Response is null or blank, internet might be down
[Info: 2022-05-07 23:07:27.8678539: GameCallbacks.cpp(177)] Game/game () Info [01:07:27] [Client thread/ERROR] [Lambda]: Response is null or blank, internet might be down`

**Comment by ghost** [comment]
I can +1 on this one as it happened to me today.

There is a test server I use for testing different mods and I had a couple donkeys I tamed on a cracked (offline) account which basically set the mob's owner to a nonexistent account.

The following error was spammed into the console: `[Lambda]: Response is null or blank, internet might be down` and if I leave it go, Mojang eventually rate-limits me.

A suggested fix is to recognize cracked/offline accounts and stop the request loop to prevent the game from freezing up and/or Mojang from rate-limiting you from their APIs.
