### ISSUE TITLE
Crystalaura bugging out

### ISSUE THREAD

**Issue by meduzzik** [lambda-client/lambda-legacy#310]
**Describe the bug**
When you use Crystalaura on any mobs or players it will not work I tried to reset settings but still.

**To Reproduce**
Go to clickgui and click crystalaura go to the nearest mob or spawn one and it will not attack it/him.

**Expected behavior**
I wanted to see working crystalaura not shit ca even kami blue is better.

**Comment by Mjaucher** [comment]
maybe you have peaceful mode

**Comment by master7720** [comment]
> **Describe the bug** When you use Crystalaura on any mobs or players it will not work I tried to reset settings but still.
> 
> **To Reproduce** Go to clickgui and click crystalaura go to the nearest mob or spawn one and it will not attack it/him.
> 
> **Expected behavior** I wanted to see working crystalaura not shit ca even kami blue is better.

could you provide a video of the ca acting weird?

**Comment by Doogie13** [comment]
\> combat settings

**Comment by ToxicAven** [comment]
There is not enough information or resources to find the issue here.

**Comment by Celse2021** [comment]
Ca does place, i have experiencied this bug, just place a crystal and it fixes, its because of multithreading calcs giving errors on some machines, so it doesnt update, so if the oponent doesnt move or if it doesnt update the calc it wont place until you place one manually.
