### ISSUE TITLE
ArrayList Rainbow custom saturation and luminance

### ISSUE THREAD

**Issue by Doogie13** [lambda-client/lambda-legacy#311]
**Is your feature request related to a problem? Please describe.**
I want to be able to change saturation and luminance of the ArrayList when using rainbow mode

**Describe the solution you'd like**
Ability to change the saturation and luminance of the Arraylist when using rainbow mode

**Describe alternatives you've considered**
Not changing the saturation and luminance of the ArrayList when using rainbow mode

**Additional context**
Ability to make it look like RusherHack ArrayList because it looks nice

**Comment by mmvanheusden** [comment]
open a pr 😂
