### ISSUE TITLE
2b2t queue returns 0 at all times

### ISSUE THREAD

**Issue by ClaraCrazy** [lambda-client/lambda-legacy#313]
**Describe the bug**
see title and attachment

**To Reproduce**
turn on queue element in HUD

**Expected behavior**
show the correct data from `https://2bqueue.info/queue`

**Debug info**

![image](https://cloud.cynthialabs.net/s/5gXd6BayppQZN6X/preview)

**Additional context / media**

![image](https://cloud.cynthialabs.net/s/TD5oxZWMB4L8cAG/preview)

**Comment by Avanatiker** [comment]
@tycrek

**Comment by Avanatiker** [comment]
Now it works again for me. can you check for you too?

**Comment by ClaraCrazy** [comment]
shows 0 0 for me

**Comment by syrenaaa** [comment]
what does it show when you open the link https://2bqueue.info/queue

**Comment by ClaraCrazy** [comment]
the correct info, as I said in my initial post..

**Comment by ClaraCrazy** [comment]
fixed itself, idk what went wrong
