### ISSUE TITLE
A few features

### ISSUE THREAD

**Issue by ClaraCrazy** [lambda-client/lambda-legacy#318]
**Is your feature request related to a problem? Please describe.**

Currently loading this together with Impact which I'd love to stop. I'm only using 3 impact features: 
- ~Chams, (renders entities like players through walls)~ I was just blind
- Hitboxes (makes hitboxes bigger)
- Auto-tool (Lambda auto-tool does not seem to work for me with "switch back" enabled, sadly)

**Describe the solution you'd like**

I'd love to see these features in lambda in the future. Having to load impact is pain and (with my limited knowledge about Minecraft) I think these features might be fairly easy additions.

If you guys want, I can open another bug report for auto-tool however other than "it doesn't work when switch back is enabled" I wouldn't have anything to add

**Comment by VerstreuteSeele** [comment]
im dumb & blind. chams and is there & auto-tool works when impact ain't loaded.. that only leaves hitboxes

**Comment by 5HT2** [comment]
> Auto-tool (Lambda auto-tool does not seem to work for me with "switch back" enabled, sadly)

How is it any different from impact for you?

**Comment by ClaraCrazy** [comment]
> > Auto-tool (Lambda auto-tool does not seem to work for me with "switch back" enabled, sadly)
> 
> How is it any different from impact for you?

When using lambda's "switch back" feature for auto-tool, it simply doesn't use auto-tool at al. It never switches to a tool. "switch-back" is enabled by default and until I turned it off, it never worked, it never selected a tool for me.

**Comment by 5HT2** [comment]
> When using lambda's "switch back" feature for auto-tool, it simply doesn't use auto-tool at al. It never switches to a tool. "switch-back" is enabled by default and until I turned it off, it never worked, it never selected a tool for me.

Are you sure this isn't a client incompatibility issue? Seems to be fine for me

**Comment by ClaraCrazy** [comment]
It happens even when I only got lambda loaded

**Comment by ToxicAven** [comment]
Hitbox expansion is nonfunctional on most servers now, and would work better as a plugin if necessary. I was unable to replicate the AutoTool issue.
