### ISSUE TITLE
[Freecam] Left Click Come: add option to target the above block 

### ISSUE THREAD

**Issue by Dano507** [lambda-client/lambda-legacy#319]
**Is your feature request related to a problem? Please describe.**
Using the Freecam module with Left Click Come enabled, I can click a block to make my character 
navigate to that block. 
However, this causes the character to break the targeted block in most cases.
This is an issue because it adds extra time to finish pathfinding, depending on the block clicked.

**Describe the solution you'd like**
2 possible solutions:
1. Set Baritone's goal above the clicked block, instead of in the clicked block
2. Add an option to enable solution 1

**Describe alternatives you've considered**
I have considered:
1. clicking nearby grass, mushrooms, flowers etc.
    - This prevents breaking blocks, but may not always be an option as it depends on the mentioned 
    blocks being nearby
2. Manually setting baritone's goal, then pathfinding
    - This also works, but is significantly longer than using Left Click Come
3. Manually cancelling Baritone with `#cancel`
    - This requires attention to cancel Baritone at the right time
4. Manually cancelling Baritone by toggling Autowalk
    - This requires attention to cancel Baritone at the right time

**Additional context**
none

**Comment by mmvanheusden** [comment]
will be adding this today

**Comment by mmvanheusden** [comment]
Done
