### ISSUE TITLE
cant turn off baritone

### ISSUE THREAD

**Issue by Mctrrt1** [lambda-client/lambda-legacy#325]
the title explans itself

**Comment by Avanatiker** [comment]
;b cancel

**Comment by Mctrrt1** [comment]
> ;b cancel

doesnt work, stops for a sec then starts again

**Comment by Avanatiker** [comment]
what modules do you have enabled

**Comment by Mctrrt1** [comment]
> what modules do you have enabled

![image](https://user-images.githubusercontent.com/106846396/171991118-f3d875e3-1a12-46d7-9109-adc22ef5cba7.png)
theese

**Comment by mmvanheusden** [comment]
try disabling antiafk

**Comment by Mctrrt1** [comment]
> try disabling antiafk

well it seems like i am so stupid i didnt realise this, thanks.
