### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Benn3557** [lambda-client/lambda-legacy#326]
It's lagging too much, i don't know why but when i turn xray on then i only have sometimes 3Fps????

**Comment by 5HT2** [comment]
This is probably a Skill related issue, this issue hasn't been reported by anyone since it was rewritten.

**Comment by Benn3557** [comment]
okay i don't really know what that means, but if i always go to a new chunk it lags.

https://user-images.githubusercontent.com/65232880/172024923-660b1301-b2fb-42f7-a2e5-f63b928d3d7a.mp4

**Comment by mmvanheusden** [comment]
do you have any other mods installed also is this only happening in single player?

**Comment by Benn3557** [comment]
No, i only had Lambda on the Mods folder. and No i played on my own server.

**Comment by ToxicAven** [comment]
If this issue is still persisting, please send latest.log, and the output of `;tsc`.

**Comment by Benn3557** [comment]
> If this issue is still persisting, please send latest.log, and the output of `;tsc`.
[latest.log](https://github.com/lambda-client/lambda/files/8870499/latest.log)

I dont really know what you mean by "output of ;tsc"

**Comment by ToxicAven** [comment]
run `;tsc` in game

**Comment by ToxicAven** [comment]
> > If this issue is still persisting, please send latest.log, and the output of `;tsc`.
> > [latest.log](https://github.com/lambda-client/lambda/files/8870499/latest.log)

This log shows lambda being used on a server which does not support such modifications. further support will not be provided.
