### ISSUE TITLE
Bigger Delay time on Spammer

### ISSUE THREAD

**Issue by BloodyNoah** [lambda-client/lambda-legacy#332]
**Is your feature request related to a problem? Please describe.**

I would like to advertise a group in the Chat, but I dont want to get annoying so I want to set the delay pretty high.

**Describe the solution you'd like**

I want to be able to set the delay to idk 3000sec with the chat commands.

**Describe alternatives you've considered**

I didnt really consider any, bc to my knowledge this should be easy to fix, but I now nothing about kotlin so here we are.

Thanks for your help

**Comment by mmvanheusden** [comment]
sure i will open a pull request today making the maximum delay higher

**Comment by syrenaaa** [comment]
Did you try to change the delay time larger through commands?

**Comment by mmvanheusden** [comment]
> Did you try to change the delay time larger through commands?

That won't work because it's still limited to the maximum value

**Comment by BloodyNoah** [comment]
> sure i will open a pull request today making the maximum delay higher

Nice, tyvm

**Comment by mmvanheusden** [comment]
Sorry that it took so long btw, i forgor :skull:

**Comment by mmvanheusden** [comment]
If you don't want to wait for the next Lambda release, you can download a development build [here](https://github.com/lambda-client/lambda/suites/6967562191/artifacts/272155190)

**Comment by BloodyNoah** [comment]
> Sorry that it took so long btw, i forgor 💀

Haha no problem and tyvm
