### ISSUE TITLE
Mod crash

### ISSUE THREAD

**Issue by haz3282** [lambda-client/lambda-legacy#341]
The game crashed whilst initializing game
Error: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.SecurityException: class "javax.annotation.Nullable"'s signer information does not match signer information of other classes in the same package
Exit Code: -1

To Reproduce

launch ig

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior

the client launched and let me play on 9b9t
Debug info

**Comment by NepNep21** [comment]
Send logs/debug.log

**Comment by haz3282** [comment]
[crash-2022-01-03_19.20.02-client.txt](https://github.com/lambda-client/lambda/files/8987641/crash-2022-01-03_19.20.02-client.txt)

**Comment by NepNep21** [comment]
That is not what i told you to send

**Comment by haz3282** [comment]
Where can i find the logs.

**Comment by NepNep21** [comment]
I already said it, logs/debug.log from your Minecraft directory
