### ISSUE TITLE
Can't send messages

### ISSUE THREAD

**Issue by DanielSTCYT** [lambda-client/lambda-legacy#342]
Hello when I try to send messages it says "Cannot send chat message" I hope anyone can help me with this thanks!
![image](https://user-images.githubusercontent.com/107445674/176435767-ab7cc589-37a9-43a7-8fab-d9a8849a3e25.png)
(Don't know if pasting the image works)

**Comment by ItCameFr0mMars** [comment]
what server are you using it on?

**Comment by DanielSTCYT** [comment]
Oldfag.org

**Comment by DanielSTCYT** [comment]
Everyone else can message

**Comment by ToxicAven** [comment]
go to "Options → Chat Settings → Chat" and set it to "Shown". This is a Minecraft Vanilla feature.
