### ISSUE TITLE
Issue with donations

### ISSUE THREAD

**Issue by Gav06** [lambda-client/lambda-legacy#35]
**Describe the bug**
Donations are being accepted

**To Reproduce**
Visit the readme

**Expected behavior**
People to not accept money for a skid

**Debug info**
N/A

**Additional context / media**
N/A

**Comment by Avanatiker** [comment]
lol the donate link does not even work :P

**Comment by huddy987** [comment]
We do a little trolling

**Comment by czho** [comment]
Its not even on the readme lmao
