### ISSUE TITLE
Self Destruct

### ISSUE THREAD

**Issue by polymo1** [lambda-client/lambda-legacy#350]
**Is your feature request related to a problem? Please describe.**

I think it would be nice to have a self-destruct feature, if something related to the client goes wrong.
**Describe the solution you'd like**

A command or clickgui option.
**Describe alternatives you've considered**

None that would suit this feature.
**Additional context**

**Comment by master7720** [comment]
💀

**Comment by mmvanheusden** [comment]
just make a binding for hud lmao

**Comment by Avanatiker** [comment]
i dont understand what you want

**Comment by mmvanheusden** [comment]
self-desuction means that the full mod unloads from the game.
This is done by some "utility mods" to hide elements from screen-sharings.
