### ISSUE TITLE
BlockEntityList for HUD

### ISSUE THREAD

**Issue by FrogsArePog** [lambda-client/lambda-legacy#357]
**Describe the solution you'd like**

I feel like there should be a feature on the HUD editor that can show you which block entities are in view and how many there are. Basically EntityList but for block entities.

**Comment by CozyMeli-gitv2** [comment]
I would imagine a better way to execute that would be to have the ability to select which entities show up on Entity List, so you can choose which entities you want. Sounds useful as fuck tbh, someone should try implementing it.
