### ISSUE TITLE
Opening new version link crashes on Linux platforms

### ISSUE THREAD

**Issue by NicholasCG** [lambda-client/lambda-legacy#360]
**Describe the bug**

When using Linux, opening the link to the newest version of the client (for me it was the link for 3.2.1) causes the game to immediately crash. From the logs, the error that occurs is:
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!

**To Reproduce**

1. Open Minecraft with an outdated version of the Lambda client.
2. Click on the red text highlighting the newest version. Crash should follow.

**Expected behavior**

It opens the link to the newest version of the client. 

**Debug info**

![image](https://user-images.githubusercontent.com/70730217/183312851-4fa7a859-602d-45c9-995a-fc028eb8de36.png)

**Additional context / media**

From my searching, this is a general problem with Java on awt's Desktop class. Desktop.browse() is not supported on Ubuntu at least.

**Comment by NepNep21** [comment]
That's interesting, i remembered browse() specifically working on gnome, in any case i will write a workaround with xdg-open if no one gets to it before me

**Comment by NicholasCG** [comment]
It would probably help clarify then that I'm using KDE.

**Comment by NepNep21** [comment]
Ah i see, installing glib may help, not sure, either way i will look into implementing it in less than 1 hour

**Comment by ToxicAven** [comment]
Known issue with KDE, java.awt.Desktop isn't great for it. I made a patch for 1.8.9 URL opening, using xdg-open, I'll post the code when I get home.

**Comment by NepNep21** [comment]
This should fix it, it will be merged into master when constructor is ready https://github.com/lambda-client/lambda/suites/7705379836/artifacts/322328761
