### ISSUE TITLE
ChestStealer's Steal Button is at wrong position

### ISSUE THREAD

**Issue by MellDa1024** [lambda-client/lambda-legacy#366]
**Describe the bug**
Steal Button is at wrong position

**To Reproduce**
1. get rusherhack
2. turn on cheststealer
3. open chest

**Expected behavior**

![stealbutton](https://user-images.githubusercontent.com/60955857/185440459-5b5ec81b-dbeb-4e7a-8a4f-4477db1888e6.png)
the steal button is at wrong position

**Debug info**

![image](https://user-images.githubusercontent.com/60955857/185440162-e0ea72bf-d0d8-43de-bd33-fb82ccaebd54.png)

**Additional context / media**
~~No matter what instance(multimc) or official launcher, it happens to whole minecraft instance when it happens.
This bug happened in my mutlimc instance "a" and after that, now it happens to multimc instance "b" and official launcher too.~~
oh yeah sorry, looks like compatibility problem with rusher.
worked well when rusher was disabled.

**Comment by rfresh2** [comment]
Resolved in https://github.com/lambda-client/lambda/pull/447
