### ISSUE TITLE
crash @ runtime

### ISSUE THREAD

**Issue by Maks7594** [lambda-client/lambda-legacy#375]
**Describe the bug**
game crashes at runtime

**To Reproduce**
1. open mc
2. crash

**Expected behavior**
it would launch

**Debug info**
it can't launch so i cant do that

**Additional context / media**
![image](https://user-images.githubusercontent.com/72873506/187060677-28f62743-7478-448b-9ad7-4225810e5d62.png)

**Comment by mmvanheusden** [comment]
Please send a crash log and the contents of your mods folder.

**Comment by liangforstudy** [comment]
Reproduce the steps, make sure that the latest version of Lambda is the only mod in the mods folder and all other mods like impact and optifine aren't in the mods folder.

Also, what's your CPU, GPU and ram specs? And how much ram is being allocated to Minecraft? Or default?

**Comment by ToxicAven** [comment]
Closing due to no information provided.
