### ISSUE TITLE
Make main menu disabled by defualt as it's laggy

### ISSUE THREAD

**Issue by Zane2b2t** [lambda-client/lambda-legacy#376]
cant even disable it need to goto lambda's config folder and turn it off with text

**Comment by NepNep21** [comment]
What even is your GPU? It should not be laggy enough to prevent you from clicking a single button.

**Comment by Zane2b2t** [comment]
> 

well i click stuff but i get like 10 fps

**Comment by CozyMeli-gitv2** [comment]
That is... a very bad graphics card of yours for sure. But ig to be fair having it off by default would prevent peeps with shit pcs having problems.

**Comment by NepNep21** [comment]
In any case, any fps issues should go away when another GUI opens, allowing you to go in game and turn it off.
