### ISSUE TITLE
Inability to load plugins.

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#380]
**Describe the bug**

Inability to load plugins, exception that I have: 
`[17:33:12] [Client thread/ERROR] [Lambda]: Missing definition. Please make sure compatible Lambda API is used.
java.lang.NoSuchMethodError: com.lambda.client.plugin.api.PluginModule.<init>(Lcom/lambda/client/plugin/api/Plugin;Ljava/lang/String;[Ljava/lang/String;Lcom/lambda/client/module/Category;Ljava/lang/String;IZZZZILkotlin/jvm/internal/DefaultConstructorMarker;)V
	at WhiteTools.<init>(WhiteTools.kt:10) ~[?:?]
	at WhiteTools.<clinit>(WhiteTools.kt) ~[?:?]
	at WhiteToolsPlugin.onLoad(WhiteToolsPlugin.kt:6) ~[?:?]`

**To Reproduce**

Use Lambda 3.2.1 & latest available plugin api (3.2?), build any plugin & drop it into lambda/plugins.

**Expected behavior**

Plugin would load as intended.

**Debug info**

**Additional context / media**

**Comment by Luigit12** [comment]
"Please make sure compatible Lambda API is used."

**Comment by ghost** [comment]
> "Please make sure compatible Lambda API is used."

 "Use Lambda 3.2.1 & **latest available plugin api (3.2?),** build any plugin & drop it into lambda/plugins."

**Comment by ToxicAven** [comment]
This user has deleted their account.
