### ISSUE TITLE
Crash at runtime

### ISSUE THREAD

**Issue by Arctic-Circle-System** [lambda-client/lambda-legacy#386]
**Describe the bug**
Upon attempting to start an instance with Lambda client, the process exits with code 1.

**To Reproduce**

1. Create a 1.12.2 instance with Forge version 14.23.5.2860 in PolyMC and make sure Java 8 is being used.
2. Put Lambda client v3.2.1 into the mods folder (I have tested this, it happens even when Lambda is the only mod in the folder)
3. Attempt to run the game. It will crash almost instantly.

**Expected behavior**
I expected the game to boot up.

**Debug info**
Here is the latest crash log https://pastebin.com/Frdzd7vZ

**Additional context / media**
Here is what showed up in PolyMC's console window https://pastebin.com/qwGimfKD

**Comment by ElBe-Plaq** [comment]
Same in Prism Launcher.

**Comment by ToxicAven** [comment]
This is very strange, just looks like forge didn't install properly. Reopen if any new details arise.
