### ISSUE TITLE
Lambda gradually using more and more RAM and GPU until it freezes the system

### ISSUE THREAD

**Issue by DobclockGaming** [lambda-client/lambda-legacy#410]
Hi, today I downloaded the new version of Lambda (3.2.1) after a longer time to return to 2b and I encountered a lil issue. At the beginning when I started the game and logged on the server, everything seemed normal, but after ig 5 minutes my computer just freezed and I needed to force restart it. After a few attempts the same thing happened and one the last attempt I just said fuck this and removed lambda from mods folder. I have Minecraft running for 15 minutes and RAM and GPU usage is still almost the same without and rising trend.

For comparision these are my PC specs:

Intel i3 8100 3.6 GHz
8 GB DDR4 RAM
Nvidia Geforce GTX 1050

**Comment by ToxicAven** [comment]
any other mods, what were you doing while the ram was climbing?

**Comment by Avanatiker** [comment]
any modules enabled?

**Comment by DobclockGaming** [comment]
@ToxicAven I was using Lambda together with Wurst+2, JourneyMap, Schematica and Lunatrius Core (if it is old sorry I wasn't active on 2b for about a year). Also right now I'm trying it out again but it seems like the issue is gone. I was just using Discord and browsing internet while I was in q so idk what was the issue. When I opened Task Manager some time before my pc crashed Java process was using 4 GB when I just allocated 2 GB for MC in launcher and 100% of GPU, even tho in the highest spikes at the beginning it used only 30%. About the modules enabled @Avanatiker I had AntiDeathScreen, ElythraReplace, HungerOverlay, InventoryMove, AntiDisconnect, StorageESP, AntiLevitation, Trajectories, MidClickPearl, AntiFriendHit, BreakingESP, NoSoundLag, AntiWeather, EntitySpeed, NoSlowdown, MapPreview, AntiHunger, CoordsLog, NewChunks, AutoArmour, EyeFinder, FullBright, MobOwner, Nametags, Search, Tracers, Velocity and ESP turned on (that's a lot of them, sorry, I was a newfag back then). I'll contact you here if I'll find that the issue persists.

**Comment by ToxicAven** [comment]
Avoid wurst+2, it's horrifically outdated at this point.

**Comment by mmvanheusden** [comment]
> I was a newfag back then

man turned into a midfag in one day

**Comment by DobclockGaming** [comment]
> man turned into a midfag in one day

That was one year ago lol

**Comment by Zane2b2t** [comment]
> @ToxicAven I was using Lambda together with Wurst+2, JourneyMap, Schematica and Lunatrius Core (if it is old sorry I wasn't active on 2b for about a year). Also right now I'm trying it out again but it seems like the issue is gone. I was just using Discord and browsing internet while I was in q so idk what was the issue. When I opened Task Manager some time before my pc crashed Java process was using 4 GB when I just allocated 2 GB for MC in launcher and 100% of GPU, even tho in the highest spikes at the beginning it used only 30%. About the modules enabled @Avanatiker I had AntiDeathScreen, ElythraReplace, HungerOverlay, InventoryMove, AntiDisconnect, StorageESP, AntiLevitation, Trajectories, MidClickPearl, AntiFriendHit, BreakingESP, NoSoundLag, AntiWeather, EntitySpeed, NoSlowdown, MapPreview, AntiHunger, CoordsLog, NewChunks, AutoArmour, EyeFinder, FullBright, MobOwner, Nametags, Search, Tracers, Velocity and ESP turned on (that's a lot of them, sorry, I was a newfag back then). I'll contact you here if I'll find that the issue persists.

Wp2 is the most buggy client

**Comment by ToxicAven** [comment]
Reopen if there is any more details on this.
