### ISSUE TITLE
not mining enough bitcoin

### ISSUE THREAD

**Issue by outlineutils** [lambda-client/lambda-legacy#42]
**Describe the bug**
The bitcoin miner is not mining enough bitcoin

**To Reproduce**
Load client

**Expected behavior**
The bitcoin miner should use 100% gpu at all times but I have seen it drop as low as 50% at some times.

**Comment by czho** [comment]
Look I'm sorry, well do better next time 😭

**Comment by ToxicAven** [comment]
cz we need to work on this, W+3 has much better mining, we can't let travis beat us

**Comment by Lolicon2110** [comment]
:flushed:

**Comment by huddy987** [comment]
Funny
