### ISSUE TITLE
"Cheese Mode" Bug

### ISSUE THREAD

**Issue by evelyn-gosselin** [lambda-client/lambda-legacy#423]
**Describe the bug**
When you go into Freecam with "Cheese Mode"
All the players around you, their heads stay in the position you put them in cheese mode. They don't reset to the position they where in before placed in cheese mode. 

**Steps to reproduce the bug**
Have a fake player, or random player A.F.K next to you.
Enable Freecam with "Cheese Mode".
Disable Freecam with "Cheese Mode".
Profit.

**Expected behavior**
I thought the players head would go back into the original position after disabling "Cheese Mode"

**Debug info**
https://imgur.com/a/JL47BS8

**Additional context / media**
Just a small bug. Nothing large.

**Comment by Avanatiker** [comment]
The second the player moves its head it will be sync again. fixing it is not worthwhile based on needed code complexity
