### ISSUE TITLE
Better Chat dosen't work with Baritone

### ISSUE THREAD

**Issue by win20-official** [lambda-client/lambda-legacy#438]
**Describe the bug**
So if you type `#help` in chat with the Better Chat mod it dosen't display the help message

**Steps to reproduce the bug**
1. Download the Better Chat mod from CurseForge
2. Get on to any server/world with Lambda Client and try to type in `#help` and it won't display the help message

**Expected behavior**
It would show the help message in chat

**Debug info**
![image](https://user-images.githubusercontent.com/80408876/208293809-47390cc9-fe24-45e2-a7e5-42c0d66208e5.png)

**Additional information**
![image](https://user-images.githubusercontent.com/80408876/208293857-dc2b7ef9-18ca-4f5a-868e-37282b228485.png)

**Comment by Avanatiker** [comment]
you can also access baritone using `;b mine diamond_ore`
