### ISSUE TITLE
Add way for plugins to enable / disable other modules.

### ISSUE THREAD

**Issue by scorbett123** [lambda-client/lambda-legacy#44]
Make it so that plugins can disable / enable different modules - these modules could be in the form of a plugin, or built into the base client.

**Comment by czho** [comment]
After we get plugins to work in a non development environment, we should do this. We also should add some integrations with our future webstore to make it way easier for people to get plugins in the first place.

**Comment by Avanatiker** [comment]
Cross referencing is already enabled again. Protecting the client core is not sufficient to guarantee any security. People just should think what to install like any mod.
