### ISSUE TITLE
KillAura not working while using Baritone

### ISSUE THREAD

**Issue by GabrieleMaurina** [lambda-client/lambda-legacy#440]
### Bug

While digging a big hole (50x50x6) using Bariton's "selection cleararea", the players gets killed by silverfish, even thiough KillAura is active.

### Steps to reproduce the bug

1. Activate KillAura  with "hostile mobs"
2. Spawn some silverfish
3. Silverfish are killed immediately thanks to KillAura
4. Using Bariton's commands, select a big underground area (50x50x6)
5. Spawn some silverfish inside the digging area
6. Before all the silverfish are all killed, run ";b s cs" (this will activate Baritone and start digging)
7. Baritone has priority over KillAura and the player dies killed by the silverfish

### Expected behavior

KillAura should have priority over Baritone, otherwise the player  dies.

### Suggested solution

KillAura should have the "pause baritone" option, like AutoEat has.

**Comment by NepNep21** [comment]
There should already be a pause baritone option in CombatSettings, that applies to all combat modules. Not sure why it wouldn't work for you, it's on by default.

**Comment by GabrieleMaurina** [comment]
![image](https://user-images.githubusercontent.com/7975169/208945370-598b6335-13a0-4805-83b7-cd3958aec8bf.png)

I did not see it. Am I looking in the wrong place?

**Comment by NepNep21** [comment]
You can change the page by clicking the page setting

**Comment by GabrieleMaurina** [comment]
Thanks, now I see it, and it is ON.

So this seem to be a bug then. Because I died several times from silverfish, while using Baritone.
