### ISSUE TITLE
Inventory glitch

### ISSUE THREAD

**Issue by WongsDongs** [lambda-client/lambda-legacy#443]
Blocks moved from hotbar and placed into main inventory snap instantly back into the hotbar. I uninstalled and reinstalled lambda and it did nothing.

https://user-images.githubusercontent.com/112718144/208791622-e1a60ce2-1a8f-49c7-aa2d-a6f7293fb48c.mp4

**Comment by agua420** [comment]
baritone issue

**Comment by Blade-ua** [comment]
Baritone settings -> Allow inventory
