### ISSUE TITLE
Tracer's barely visible at max thickness

### ISSUE THREAD

**Issue by Toastical** [lambda-client/lambda-legacy#445]
**Describe the bug**
Tracer's barely visible even at max thickness

**Expected behavior**
Tracers to be clearer, less jittery

**Debug info**
https://i.imgur.com/axhTdMk.png

**Additional context / media**
https://i.imgur.com/9YdyuXx.png
https://i.imgur.com/2DTRxLz.png

**Comment by Avanatiker** [comment]
Do you use any other mods? it should normally look like this:
![image](https://user-images.githubusercontent.com/8580605/222341939-4698ec6c-5e9a-4619-b608-e90dc5f242ef.png)

**Comment by Toastical** [comment]
> Do you use any other mods? it should normally look like this: ![image](https://user-images.githubusercontent.com/8580605/222341939-4698ec6c-5e9a-4619-b608-e90dc5f242ef.png)

Apologies for the late reply. I tend to use Optifine (HD U G5), but the issue persists with Optifine disabled as well. A friend mentioned that it's an AMD issue (?). ~~Supposedly Future and Rusher have it fixed.~~ They do not.

**Comment by Toastical** [comment]
Downgrading my drivers to the ones released in May has fixed the tracer issue. So it is a driver issue by AMD!
