### ISSUE TITLE
Setting option for each server

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#45]
For example when u log in to 2b2t the cpvp  settings of rage will be the most u can get in 2b2t. And in another server like ec.me it will change to the max settings u can have at this server

**Comment by scorbett123** [comment]
I believe that this is already possible ([here is a video of it I found in the Kami Blue discord](https://cdn.discordapp.com/attachments/789630848194183209/797210590853464064/server_presets.mp4))

**Comment by Natan515** [comment]
No, that is something else, I wan t default option to change from any server

**Comment by ToxicAven** [comment]
This is possible using the module "Configurations"

**Comment by Natan515** [comment]
Again, it is not default, and I want it to be default (added to the json file)

**Comment by ToxicAven** [comment]
I need you to elaborate on that

**Comment by Natan515** [comment]
> I need you to elaborate on that

Well, you know that u go to a cpvp server or another one of those clown anarchy server and want to already have the best possible pvp settings for this server? So some people will check it and put it on default when u join this spastic server.

**Comment by Avanatiker** [comment]
Would need non reasonably much maintaining effort to keep it updated. Maybe make a plugin?
