### ISSUE TITLE
Discord rpc doesn't show picture

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#47]
![Screenshot (22)](https://user-images.githubusercontent.com/66911017/116900594-92c27000-ac41-11eb-8120-8acfc5a8e277.png)

**Comment by ToxicAven** [comment]
This is because we do not have a logo as of now. When we get one, it will be added there.

**Comment by Natan515** [comment]
> This is because we do not have a logo as of now. When we get one, it will be added there.

Great!

**Comment by Avanatiker** [comment]
someone told me that it works when someone else looks at the rpc in discord. because we already have set up the logo

**Comment by Natan515** [comment]
I don't think this is correct, I mean it doesn't make any technical sanse; but naybe.

**Comment by Natan515** [comment]
I see it's fixed
![Screenshot (15)](https://user-images.githubusercontent.com/66911017/119549298-bfc8f500-bd9f-11eb-9e2e-88f0d78eb151.png)
