### ISSUE TITLE
Add creative fly button to sprint 

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#48]
Like when ur flying or using an elytra, and its rly annoying

**Comment by Luna5ama** [comment]
Turn off Check Flying

**Comment by Natan515** [comment]
> Turn off Check Flying

Why can't it be default... ?

**Comment by Luna5ama** [comment]
> > Turn off Check Flying
> 
> Why can't it be default... ?

It messes up with the speed if you are using elytra flight

**Comment by Natan515** [comment]
Can't we have 1 button for elytra and one for normal creative flying?

**Comment by Natan515** [comment]
Is it possible? @Xiaro
