### ISSUE TITLE
Can't get on the game

### ISSUE THREAD

**Issue by ToxicReno** [lambda-client/lambda-legacy#483]
**Describe the bug**
  Wont load up

**Steps to reproduce the bug**

1. Go to 'Open Minecraft Launcher'
2. Click on 'Play'
3. Crashed
 

Heres my spects  Device name RenoComputer
Processor AMD Ryzen 5 5500U with Radeon Graphics 2.10 GHz
Installed RAM 12.0 GB (11.3 GB usable)
Device ID A680AA78-8EE5-4417-8474-CA60A58AC389
Product ID 00342-21979-06555-AAOEM
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**Comment by agua420** [comment]
crashlog

**Comment by ToxicReno** [comment]
1\\

**Comment by ToxicReno** [comment]
1

**Comment by ToxicAven** [comment]
If you could send the crashlog at `.minecraft/logs/latest.log` that would help.

**Comment by ToxicAven** [comment]
No crash log has been provided, feel free to reopen with a crash log.
