### ISSUE TITLE
Add parkour

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#49]
Add parkour, so the player will jump when it gets to the end of the block.

**Comment by ToxicAven** [comment]
This has already been added here: https://github.com/lambda-client/lambda/pull/27

**Comment by Natan515** [comment]
Ye, I did remember u had this pull req but I thought u didn't added it. Well thanks!

**Comment by Luna5ama** [comment]
This shouldn't be closed until the pr is merged

**Comment by ToxicAven** [comment]
> This shouldn't be closed until the pr is merged

This PR will not be merged, as the feature will be part of the plugins system.
