### ISSUE TITLE
Map downloader bug

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#490]
1. Go to 'Map downloader.'
2. Click on ' open image folder' (and i cant turn it off)
3. Restart lambda
4. See always folder on start

open_image_folder...": true so it true, and in game i cant turn it to off, so i renamed true to false and i fixed this

**Comment by Avanatiker** [comment]
fixed in latest nightly

**Comment by ghost** [comment]
> fixed in latest nightly
thanks, pls see: https://github.com/lambda-client/lambda/issues/499
