### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#499]
Banned MISHA#0045. banned Ромбоикосододекаэдр
#3107 , for reason this is my twink, but it not my twink, i dont have twinks/ 

he wrote something in the chat and I was banned too, you can ban on ip Ромбоикосододекаэдр
#3107, but not misha, if im misha i cant join because Ромбоикосододекаэдр
#3107 banned for ip

**Comment by ghost** [comment]
and any proof for twink? no, YOU BANNED ME

**Comment by Blade-ua** [comment]
annoying

**Comment by blauefeuerr** [comment]
bro the Ромбоикосододекаэдр#3107 isn't a twink!

**Comment by ghost** [comment]
> annoying

yes

**Comment by blauefeuerr** [comment]
Waiting for unban.

**Comment by F3F5** [comment]
and what the fuck do I have  ban? i muted for ru chat only and waiting unmute but you banned me, thanks, poor moderation system

**Comment by ghost** [comment]
hello
