### ISSUE TITLE
[bug] Wrong FPS and TPS calculation

### ISSUE THREAD

**Issue by tycrek** [lambda-client/lambda-legacy#5]
**Describe the bug**

Title.

**To Reproduce**

1. Turned on Kami Blue FPS HUD
2. I turned on the FPS HUD and adjusted smooth lighting setting & GUI Scale setting for MC
3. Time travelled ass backwards into next week

**Expected behavior**

Don't time travel ass backwards into next week

**Debug info**

![image](https://user-images.githubusercontent.com/29926144/116158457-f5e55d00-a6ab-11eb-9553-cb6615a6d9b8.png)

**Additional context / media**

LAMBDA CLIENT ON TOP SOON TM

**Comment by czho** [comment]
lambda client is just so good, its time traveling
