### ISSUE TITLE
Strange working jesus

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#506]
**Describe the bug**
When I turn on the dolphin mode, it walks on the water and does not swim

**Expected behavior**
Bug after recode jesus

**Discord**
MISHA#0045 banned but I didn't break anything for ban
some info: https://github.com/lambda-client/lambda/issues/499

**Comment by Doogie13** [comment]
Can you please send a video?

**Comment by ghost** [comment]
> 


https://user-images.githubusercontent.com/108226177/222728962-a0eb46ba-c5b4-447e-933e-863a0a2ed9ce.mp4

**Comment by ghost** [comment]
> Can you please send a video?

done

**Comment by Doogie13** [comment]
You are bobbing up and down like Dolphin jesus should. It shouldn't go as low as the old one did.
