### ISSUE TITLE
gui is broken

### ISSUE THREAD

**Issue by truong0235** [lambda-client/lambda-legacy#507]
just installed 1 hour ago, tried to fix the gui but nothing happened

![image](https://user-images.githubusercontent.com/53035575/222917321-705ee424-84d8-4c1e-9dbe-b30d2c2fe444.png)

![image](https://user-images.githubusercontent.com/53035575/222917554-385a5c0b-e61c-4410-a580-bb7fb71af388.png)

mod installed: optifine, viaforge, lambda client

os: windows 7, 64 bit

**Comment by emyfops** [comment]
Remove optifine

**Comment by truong0235** [comment]
> Remove optifine

doesnt work

**Comment by N-Nels0n** [comment]
You probably just messed up with the LOD Bias setting in CustomFont.
`;set CustomFont lodbias 0` should fix it.
Othewise you probably just got a bad GPU.
