### ISSUE TITLE
UNEXPECTED CRASH ON STARTUP

### ISSUE THREAD

**Issue by BunnyNotFoundXD** [lambda-client/lambda-legacy#508]
**Describe the bug**
I am getting Issue that, my forge is not loading while using lambda.

**Steps to reproduce the bug**

1. Go to 'forge 1.12.2'
2. Click on 'Play with lamda mod'
3.See error

**Expected behavior**
I expected game to run

**Debug info**
--- Minecraft Crash Report ----

WARNING: coremods are present:
  LambdaCoreMod (Lambda-Client-Mod-Forge-1.12.2.jar)
Contact their authors BEFORE contacting forge

**Comment by CozyMeli-gitv2** [comment]
that is not a crash report. provide latest.log

**Comment by BunnyNotFoundXD** [comment]
[crash-2023-03-04_05.19.47-client.txt](https://github.com/lambda-client/lambda/files/10918063/crash-2023-03-04_05.19.47-client.txt)

[latestlog.txt](https://github.com/lambda-client/lambda/files/10918071/latestlog.txt)

**Comment by BunnyNotFoundXD** [comment]
@CozyMeli-gitv2 Can you please help regarding this issue?

**Comment by BunnyNotFoundXD** [comment]
You have your discord in your profile :l nothing 5o track

**Comment by PoTheMagicDragon** [comment]
Lambda doesn't play well with Optifine. Does removing that fix your problem?

**Comment by hexadec1mal** [comment]
You launch the game using pojavLauncher(on android) and you have 32 bit device. Lambda client developers can't fix this
