### ISSUE TITLE
Allow keyboard shortcuts in String settings

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#51]
Something like Ctrl + t

**Comment by Avanatiker** [comment]
Used in what circumstance?

**Comment by Natan515** [comment]
When u got too much different stuff u want to enable by ur keyboard but don't got enough keys that r easy to use

**Comment by Avanatiker** [comment]
So you jsut want to add support for button combinations right?

**Comment by Natan515** [comment]
Yes

**Comment by scorbett123** [comment]
Button combinations are already possible,  this issue I think really should address editing string settings.
