### ISSUE TITLE
Make a way to add blocks to de search list easier, so we dont have to write commands for every block we want to search especially different colored shulkers. 

### ISSUE THREAD

**Issue by JaTabs** [lambda-client/lambda-legacy#521]
Its frustrating to put so many commands to search for some blocks. Maybe a menu like impact that you can select the blocks you want without having to write so many commands.

**Comment by jaaloley** [comment]
What are the commands? Still havent figured out how to add blocks

**Comment by kdh8219** [comment]
Already completed 77d66d9
