### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Aholicknight** [lambda-client/lambda-legacy#525]
I am using the latest version, and I am trying to use lambda client with a forge modpack. I also added a ! to make sure, lambda loads first, but I still crash. My full log can be viewed here: https://paste.ee/p/LfSvg

**Comment by ToxicAven** [comment]
Lambda does not support use outside of anarchy settings.

**Comment by Aholicknight** [comment]
I see, well thank you for the clarification.
