### ISSUE TITLE
Add HitBox, AutoClicker and Reach

### ISSUE THREAD

**Issue by Netrinix** [lambda-client/lambda-legacy#527]
I'm always frustrated when i in a high anticheat server fighting(use sword and crystal). because,  when i use killaura, i'll kicked. but , the hitbox, autoclicker and reach are very safe, anticheat can't see me cheating! can you add these modules to combat category?

**Comment by Netrinix** [comment]
Thank you!

**Comment by Blade-ua** [comment]
Cheater!

**Comment by kdh8219** [comment]
# [Disclaimer](https://github.com/lambda-client/lambda#disclaimer)

> This is a Forge utility mod, ***only meant for use in anarchy environments.*** Do not use without permission of server administration.

**Comment by Netrinix** [comment]
> # [Disclaimer](https://github.com/lambda-client/lambda#disclaimer)
> > This is a Forge utility mod, _**only meant for use in anarchy environments.**_ Do not use without permission of server administration.

but i using it at 2b2t.xin(a anarchy server)!
