### ISSUE TITLE
Elytra fly hack that works on 2b2t

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#54]
Fix elytra closing with Boost mode

**Comment by FluorideHistorian** [comment]
already in the client

**Comment by Natan515** [comment]
@FluorideHistorian  Can u pls show me the method to do so?

**Comment by FluorideHistorian** [comment]
its boost mode but i dont have the specific method for lambda

**Comment by Natan515** [comment]
Ok.

**Comment by czho** [comment]
Boost mode works, kinda. Hause added a patch to make it very difficult to open elytra after it closes, this happens alot when using boost mode, it does it randomly. TLDR: make timer takeoff great again.

**Comment by Natan515** [comment]
Ok so I need to reopen it again lol
