### ISSUE TITLE
KIllaura Targtets

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#588]
**Is your feature request related to a problem? Please elaborate.**
not exactly, just would be nice

**Describe the solution or feature you'd like implemented.**
configurable targets in killaura like ESP [(this image)](https://github.com/lambda-client/lambda/assets/144849202/e1e17355-6c2c-4319-bb08-0b99155534e2)

**Describe alternatives you've considered.**
using other clients but dont really like them

**Comment by emyfops** [comment]
You can edit the kill aura targets via the CombatSetting module

**Comment by ghost** [comment]
Oh sorry
