### ISSUE TITLE
Pojavlauncher game exited with code-1

### ISSUE THREAD

**Issue by CHOPDAHEADYT** [lambda-client/lambda-legacy#593]
[crash-2024-09-08_16.12.25-client.txt](https://github.com/user-attachments/files/16921851/crash-2024-09-08_16.12.25-client.txt)
**Describe the bug**

I downloaded mods and opened Forge 1.8.9 it keeps crashing and shows game exited with code -1
**Steps to reproduce the bug**

Put mods in folder 
Open 1.8.9 forge
I get the minecraft screen and it crashes 
Seen error  game exited with code-1
[crash-2024-09-08_16.12.25-client.txt](https://github.com/user-attachments/files/16921860/crash-2024-09-08_16.12.25-client.txt)
![Screenshot_20240908_161233_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/5e73b3cf-4801-4785-9372-67c5e88c9d39)
](url)

**Comment by emyfops** [comment]
- Pojav launcher is not supported
- Lambda is a 1.12.2 mod only

You can close this issue

**Comment by CHOPDAHEADYT** [comment]
But do u know how to fix?

**Comment by emyfops** [comment]
> But do u know how to fix?

There crash is not even related to lambda
Did you take the time to check the logs ?

**Comment by CHOPDAHEADYT** [comment]
How to close
