### ISSUE TITLE
Add self web

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#62]
So u can put web where ur standing right now so if someone's jumps to u; u can crystal the hell out of him.

**Comment by Doogie13** [comment]
This should be closed by avens plugin

**Comment by Natan515** [comment]
#113

**Comment by luxuwu** [comment]
the highwaytools is very bugged due to it trying to place a block throw a block and it just brakes and gets stuck add a setting to tern this off or something idk
