### ISSUE TITLE
Add Search for moudle

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#64]
Like in Meteor that u can write something and it will show u the module, like ctrl + f

**Comment by ToxicAven** [comment]
Literally already does this when you begin typing with the ClickGUI open.

**Comment by Natan515** [comment]
Oh. we really need to create a wiki for this client, there are a lot of stuff a lot of people don't know (like me)

**Comment by ToxicAven** [comment]
> 
> 
> Oh. we really need to create a wiki for this client, there are a lot of stuff a lot of people don't know (like me)

Agreed, that should be part of the website using some Jekyll docs engine thing.

**Comment by Natan515** [comment]
We need to create a wiki in the github. and maybe something in the discord server

**Comment by ToxicAven** [comment]
> 
> 
> We need to create a wiki in the github. and maybe something in the discord server

You missed my point. Jekyll is a website engine, and we can make the wiki through a Jekyll page. Github Wikis are not good. and why would we make wiki stuff in the discord when there is a perfectly good wiki online?
