### ISSUE TITLE
Allow people to pull req changes to the wiki 

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#66]
To the GitHub, and a link with a commend .wiki or .help. Where we can explain stuff to noobs like me

**Comment by ToxicAven** [comment]
Honestly, Github wikis are not that good. We will most likely use something with Jekyll. The command to access the wiki is a good idea.

**Comment by Avanatiker** [comment]
Whats wrong with the github wiki?

**Comment by ToxicAven** [comment]
> 
> 
> Whats wrong with the github wiki?

Its just clunky. Jekyll looks much better and functions better as well.

**Comment by Avanatiker** [comment]
Still would be nice to have everything in one place. You can talk with Enigma about a system if u want to

**Comment by Natan515** [comment]
K

**Comment by Avanatiker** [comment]
Done
