### ISSUE TITLE
Add PVP bot 

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#78]
PVP bot like in summit client - https://github.com/THCFree/summit-client-full
So people can fight like they are pros while they r noobs, and people can use bots to help them pvp

**Comment by ToxicAven** [comment]
No. This client is not based around PVP like Summit or Momentum, and would just be a source of confusion.

**Comment by Natan515** [comment]
Maybe not based on it but it can use some better pvp modules

**Comment by scorbett123** [comment]
This should probably be a plugin though, that would hopefully reduce the confusion.

**Comment by ToxicAven** [comment]
If at all. I don't see why someone should waste their time developing a PVP bot for a client not focused on PVP. We should have a bounty board for plugins, because I see no reason for people to make this without incentive.

**Comment by Natan515** [comment]
We can make it as a long term thing

**Comment by Avanatiker** [comment]
Who said we don't do pvp?

**Comment by Natan515** [comment]
No one... @ToxicAven just said we don't focus on PVP

**Comment by Natan515** [comment]
I mean, I believe we should focus more on pvp

**Comment by KMatias123** [comment]
Most users compare clients by how good pvp modules they have
