### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by ghost** [lambda-client/lambda-legacy#82]
title screen shaders skidded from xulu client without giving credit to elementars

**Comment by czho** [comment]
Which files are the stolen code in?

**Comment by ghost** [comment]
every single one of the glsl shaders

**Comment by ghost** [comment]
https://github.com/Gopro336/XULU_Buildable_SRC/tree/master/src/main/resources/shaders

**Comment by ghost** [comment]
https://github.com/lambda-client/lambda/tree/master/src/main/resources/assets/minecraft/shaders/menu

**Comment by ghost** [comment]
look familiar?

**Comment by Avanatiker** [comment]
Lol its not like XULU own the shaders :P they have a different origin http://glslsandbox.com/ they are open source and we left all comments of ORIGINAL creators inside the code.
