### ISSUE TITLE
Add a way to completely remove Lambda client

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#84]
So it will remove all the folders and stuff, for people that aren't sure what is a part of lambda client and what is just Minecraft stuff they remove. Have in some kind of a commend that u need to press a few times to ensure u want to remove it.

**Comment by ToxicAven** [comment]
This is not a useful feature. Lambda uses 1 folder, and removing it is pointless.

**EDIT**
Possibly when we refactor the installer, i suppose

**Comment by Natan515** [comment]
Well it shouldn't be that complected to add this feature so I believe it worths it

**Comment by Doogie13** [comment]
its 1 folder lmao

**Comment by ToxicAven** [comment]
It will be brought up when the installer is refactored. As of now it is completely useless.

**Comment by Natan515** [comment]
But it would be able to maybe also remove all old version of lambda jar from ur computer

**Comment by Natan515** [comment]
And just an option to remove old jar of lambda client, and old kami blue stuff

**Comment by ToxicAven** [comment]
This is extraordinarily useless.

**Comment by czho** [comment]
im not sure this is needed

**Comment by ToxicAven** [comment]
We'll add it as an option in the installer i suppose, just for appeasement lmao

**Comment by Avanatiker** [comment]
I just removed the installer lol

**Comment by ToxicAven** [comment]
> 
> 
> I just removed the installer lol

When we refactor it to something similar to the Rusherhack installer(?) we could maybe add a remove function

**Comment by Luna5ama** [comment]
Impact self destruction
