### ISSUE TITLE
AutoTrap Isnt trapping

### ISSUE THREAD

**Issue by USAFAN** [lambda-client/lambda-legacy#85]
Please make AutoTrap incorporate the Full Trap Method instead of using surround offset. (its only surrounding others as of right now). Also it has issues placing near echests resulting in a kick or staying in the echest gui until module is toggled off.

**Comment by Avanatiker** [comment]
its planned to integrate the advanced building engine of highwaytools into lambda to make all plugins use this system. wait till that rewrite.
