### ISSUE TITLE
Some modules dont seem to work on ARM

### ISSUE THREAD

**Issue by terrified9** [lambda-client/lambda-legacy#86]
**Describe the bug**
Killaura and crystalaura dont attack players on ARM (aarch-64) cpu architecture, and commands also dont work.

**To Reproduce**

1. Install lambda client on an android phone (or any other ARM device)
2. Go into multiplayer or singleplayer
3. Try activating killaura, and you will see how it doesnt attack
4. Also try putting any chat command, and it will also not work

**Expected behavior**
Killaura should attack players, chat commands should work as they are supposed to

**Debug info**
Commands dont work, im using latest actions build

**Additional context / media**
https://streamable.com/vz7690

**Comment by terrified9** [comment]
Alsk i tried without any mods, ony lambda and still doesnt work

**Comment by ToxicAven** [comment]
At the moment, ARM Processor architectures are not supported by Lambda.

**Comment by terrified9** [comment]
Oh ok i got it running by removing discordrpc totally but then i think ill just wait :)

**Comment by czho** [comment]
Good thing you got it working, arm is the future!
