### ISSUE TITLE
plugin: Debug Helper

### ISSUE THREAD

**Issue by scorbett123** [lambda-client/lambda-legacy#93]
A plugin that doesn't appear on normal lists (only really for devs) that allows easy access to items from outside the client, for example logs whilst trying to test plugins (live logs).

I could also have the ability to show the status of other things inside the client if they are deemed to be something that is necessary.

**Comment by Avanatiker** [comment]
What kind of information u want to have debuged?

**Comment by scorbett123** [comment]
live logs mainly, one main feature it could have is de mapping log files. This would of course mainly be used outside of a dev env so everything would have unhelpful names. It would aid in the further development of more plugins.

**Comment by scorbett123** [comment]
Could have probably explained this better, but basically a log deobfuscator.
